function(termatrix_install_layout library_target cached_meta_files)
  install(TARGETS ${library_target} ARCHIVE DESTINATION lib)
  install(FILES "${CMAKE_SOURCE_DIR}/include/termatrix/matrix.h" DESTINATION include/termatrix)
  install(FILES "${CMAKE_SOURCE_DIR}/include/termatrix/detail/export.h" DESTINATION include/termatrix/detail)
  install(FILES "${CMAKE_SOURCE_DIR}/include/termatrix/detail/abi_codes.h" DESTINATION include/termatrix/detail)
  foreach(meta_file IN LISTS cached_meta_files)
    get_filename_component(meta_name "${meta_file}" NAME)
    install(FILES "${meta_file}" DESTINATION share/termatrix RENAME "${meta_name}")
  endforeach()
  install(FILES "${CMAKE_SOURCE_DIR}/docs/release-contract.md" DESTINATION share/termatrix)
endfunction()
