# Interface capsule authority for the glibc release target.
set(TERMATRIX_INTERFACE_ABI_DEFINE "TERMATRIX_ABI_GLIBC")
set(TERMATRIX_INTERFACE_TARGET_DEFINE "TERMATRIX_TARGET_GLIBC_X86_64")
set(TERMATRIX_INTERFACE_PROFILE "gnu-glibc")
