# Interface capsule authority for the musl release target.
set(TERMATRIX_INTERFACE_ABI_DEFINE "TERMATRIX_ABI_MUSL")
set(TERMATRIX_INTERFACE_TARGET_DEFINE "TERMATRIX_TARGET_MUSL_X86_64")
set(TERMATRIX_INTERFACE_PROFILE "musl-gcc")
