#!/usr/bin/env bash
set -euo pipefail
cd /app

cp "${ROOT_DIR}/patches/audit/AuditEngine.java" "src/main/java/dev/terminus/trivia/audit/AuditEngine.java"
cp "${ROOT_DIR}/patches/audit/AuditIssue.java" "src/main/java/dev/terminus/trivia/audit/AuditIssue.java"
cp "${ROOT_DIR}/patches/audit/AuditResult.java" "src/main/java/dev/terminus/trivia/audit/AuditResult.java"
cp "${ROOT_DIR}/patches/audit/AuditState.java" "src/main/java/dev/terminus/trivia/audit/AuditState.java"
cp "${ROOT_DIR}/patches/audit/ReportWriter.java" "src/main/java/dev/terminus/trivia/audit/ReportWriter.java"
cp "${ROOT_DIR}/patches/audit/StateStore.java" "src/main/java/dev/terminus/trivia/audit/StateStore.java"
cp "${ROOT_DIR}/patches/cli/AuditCommand.java" "src/main/java/dev/terminus/trivia/cli/AuditCommand.java"
cp "${ROOT_DIR}/patches/cli/ExitCodes.java" "src/main/java/dev/terminus/trivia/cli/ExitCodes.java"
cp "${ROOT_DIR}/patches/cli/Main.java" "src/main/java/dev/terminus/trivia/cli/Main.java"
cp "${ROOT_DIR}/patches/cli/PlaythroughCommand.java" "src/main/java/dev/terminus/trivia/cli/PlaythroughCommand.java"
cp "${ROOT_DIR}/patches/config/ConfigLoader.java" "src/main/java/dev/terminus/trivia/config/ConfigLoader.java"
cp "${ROOT_DIR}/patches/config/ConfigSource.java" "src/main/java/dev/terminus/trivia/config/ConfigSource.java"
cp "${ROOT_DIR}/patches/config/DungeonConfig.java" "src/main/java/dev/terminus/trivia/config/DungeonConfig.java"
cp "${ROOT_DIR}/patches/dataset/DuckDbCatalog.java" "src/main/java/dev/terminus/trivia/dataset/DuckDbCatalog.java"
cp "${ROOT_DIR}/patches/dataset/LegacyLocatorResolver.java" "src/main/java/dev/terminus/trivia/dataset/LegacyLocatorResolver.java"
cp "${ROOT_DIR}/patches/dataset/QuestionFingerprint.java" "src/main/java/dev/terminus/trivia/dataset/QuestionFingerprint.java"
cp "${ROOT_DIR}/patches/dataset/QuestionLocator.java" "src/main/java/dev/terminus/trivia/dataset/QuestionLocator.java"
cp "${ROOT_DIR}/patches/dataset/QuestionRecord.java" "src/main/java/dev/terminus/trivia/dataset/QuestionRecord.java"
cp "${ROOT_DIR}/patches/manifest/ArtifactKind.java" "src/main/java/dev/terminus/trivia/manifest/ArtifactKind.java"
cp "${ROOT_DIR}/patches/manifest/ArtifactScanner.java" "src/main/java/dev/terminus/trivia/manifest/ArtifactScanner.java"
cp "${ROOT_DIR}/patches/manifest/LoadedArtifact.java" "src/main/java/dev/terminus/trivia/manifest/LoadedArtifact.java"
cp "${ROOT_DIR}/patches/manifest/TomlJsonLoader.java" "src/main/java/dev/terminus/trivia/manifest/TomlJsonLoader.java"
cp "${ROOT_DIR}/patches/manifest/YamlJsonLoader.java" "src/main/java/dev/terminus/trivia/manifest/YamlJsonLoader.java"
cp "${ROOT_DIR}/patches/play/AnswerScript.java" "src/main/java/dev/terminus/trivia/play/AnswerScript.java"
cp "${ROOT_DIR}/patches/play/PlaythroughEngine.java" "src/main/java/dev/terminus/trivia/play/PlaythroughEngine.java"
cp "${ROOT_DIR}/patches/play/PlaythroughResult.java" "src/main/java/dev/terminus/trivia/play/PlaythroughResult.java"
cp "${ROOT_DIR}/patches/play/ScoringEngine.java" "src/main/java/dev/terminus/trivia/play/ScoringEngine.java"
cp "${ROOT_DIR}/patches/registry/DungeonRegistry.java" "src/main/java/dev/terminus/trivia/registry/DungeonRegistry.java"
cp "${ROOT_DIR}/patches/registry/EncounterNode.java" "src/main/java/dev/terminus/trivia/registry/EncounterNode.java"
cp "${ROOT_DIR}/patches/registry/GraphValidator.java" "src/main/java/dev/terminus/trivia/registry/GraphValidator.java"
cp "${ROOT_DIR}/patches/registry/RegistryBuilder.java" "src/main/java/dev/terminus/trivia/registry/RegistryBuilder.java"
cp "${ROOT_DIR}/patches/registry/RegistryDigests.java" "src/main/java/dev/terminus/trivia/registry/RegistryDigests.java"
cp "${ROOT_DIR}/patches/registry/RoomNode.java" "src/main/java/dev/terminus/trivia/registry/RoomNode.java"
cp "${ROOT_DIR}/patches/schema/SchemaCatalog.java" "src/main/java/dev/terminus/trivia/schema/SchemaCatalog.java"
cp "${ROOT_DIR}/patches/schema/SchemaValidator.java" "src/main/java/dev/terminus/trivia/schema/SchemaValidator.java"
cp "${ROOT_DIR}/patches/schema/ValidationFinding.java" "src/main/java/dev/terminus/trivia/schema/ValidationFinding.java"
cp "${ROOT_DIR}/patches/util/CanonicalJson.java" "src/main/java/dev/terminus/trivia/util/CanonicalJson.java"
cp "${ROOT_DIR}/patches/util/Digest.java" "src/main/java/dev/terminus/trivia/util/Digest.java"
cp "${ROOT_DIR}/patches/util/PathUtil.java" "src/main/java/dev/terminus/trivia/util/PathUtil.java"
cp "${ROOT_DIR}/patches/util/UnicodeNormalizer.java" "src/main/java/dev/terminus/trivia/util/UnicodeNormalizer.java"

