#!/usr/bin/env bash
set -euo pipefail
cat > /app/task_file/src/main.rs <<'RUST'
use std::{collections::BTreeMap,env,fs};
#[derive(Clone)]struct Row{x:Vec<Option<f64>>,y:String,w:f64}
enum Node{Leaf(BTreeMap<String,f64>),Split{f:usize,t:f64,l:Box<Node>,r:Box<Node>,lp:f64}}
fn main(){if let Err(e)=run(){eprintln!("{e}");std::process::exit(2)}}
fn table(p:&str)->Result<(Vec<String>,Vec<Vec<String>>),String>{let s=fs::read_to_string(p).map_err(|_|"read")?;let mut i=s.lines();let h=i.next().ok_or("header")?.split('\t').map(str::to_string).collect();let r=i.filter(|x|!x.is_empty()).map(|x|x.split('\t').map(str::to_string).collect()).collect();Ok((h,r))}
fn run()->Result<(),String>{let a:Vec<_>=env::args().collect();if a.len()!=4{return Err("arguments".into())}let(th,tr)=table(&a[1])?;let(ph,pr)=table(&a[2])?;let cs=fs::read_to_string(&a[3]).map_err(|_|"config")?;let cr:Vec<Vec<String>>=cs.lines().filter(|x|!x.is_empty()).map(|x|x.split('\t').map(str::to_string).collect()).collect();if th.len()<4||th[0]!="id"||th[th.len()-2]!="label"||th[th.len()-1]!="weight"||ph.len()!=th.len()-2||ph[0]!="id"||ph[1..]!=th[1..th.len()-2]{return Err("schema".into())}
 let mut md=None;let mut ml=None;for v in cr{if v.len()!=2{return Err("config".into())}match v[0].as_str(){"max_depth"=>md=Some(v[1].parse::<usize>().map_err(|_|"depth")?),"min_leaf_weight"=>ml=Some(v[1].parse::<f64>().map_err(|_|"leaf")?),_=>return Err("config key".into())}}let(md,ml)=(md.ok_or("depth")?,ml.ok_or("leaf")?);if ml<=0.0{return Err("leaf".into())}
 let nf=th.len()-3;let mut rows=Vec::new();for v in tr{if v.len()!=th.len(){return Err("row".into())}let w:f64=v[v.len()-1].parse().map_err(|_|"weight")?;if !w.is_finite()||w<=0.0{return Err("weight".into())}let mut x=Vec::new();for z in &v[1..1+nf]{x.push(if z=="?"{None}else{Some(z.parse().map_err(|_|"feature")?)})}rows.push(Row{x,y:v[v.len()-2].clone(),w})}
 if rows.is_empty(){return Err("empty".into())}let names=&th[1..1+nf];let samples:Vec<_>=(0..rows.len()).map(|i|(i,rows[i].w)).collect();let tree=build(&rows,names,&samples,0,md,ml);
 print!("{{\"predictions\":[");for(k,v)in pr.iter().enumerate(){if v.len()!=ph.len(){return Err("predict row".into())}let mut x=Vec::new();for z in &v[1..]{x.push(if z=="?"{None}else{Some(z.parse().map_err(|_|"feature")?)})}let d=predict(&tree,&x);let(label,p)=d.iter().max_by(|a,b|a.1.partial_cmp(b.1).unwrap().then_with(||b.0.cmp(a.0))).unwrap();if k>0{print!(",")}print!("{{\"id\":\"{}\",\"label\":\"{}\",\"probability\":{:.6}}}",v[0],label,p)}println!("]}}");Ok(())}
fn dist(rows:&[Row],s:&[(usize,f64)])->BTreeMap<String,f64>{let mut d=BTreeMap::new();let z:f64=s.iter().map(|x|x.1).sum();for(i,w)in s{*d.entry(rows[*i].y.clone()).or_insert(0.0)+=*w/z}d}
fn gini(rows:&[Row],s:&[(usize,f64)])->f64{1.0-dist(rows,s).values().map(|p|p*p).sum::<f64>()}
fn build(rows:&[Row],names:&[String],s:&[(usize,f64)],dep:usize,max:usize,min:f64)->Node{let base=gini(rows,s);if dep>=max||base<1e-15{return Node::Leaf(dist(rows,s))}let total:f64=s.iter().map(|x|x.1).sum();let mut best:Option<(f64,String,f64,usize,f64)>=None;
 for f in 0..names.len(){let mut vals:Vec<f64>=s.iter().filter_map(|(i,_)|rows[*i].x[f]).collect();vals.sort_by(|a,b|a.partial_cmp(b).unwrap());vals.dedup();for z in vals.windows(2){let t=(z[0]+z[1])/2.0;let lw:f64=s.iter().filter(|(i,_)|rows[*i].x[f].is_some_and(|v|v<=t)).map(|x|x.1).sum();let rw:f64=s.iter().filter(|(i,_)|rows[*i].x[f].is_some_and(|v|v>t)).map(|x|x.1).sum();if lw==0.0||rw==0.0{continue}let lp=lw/(lw+rw);let mut l=Vec::new();let mut r=Vec::new();for(i,w)in s{match rows[*i].x[f]{Some(v)if v<=t=>l.push((*i,*w)),Some(_)=>r.push((*i,*w)),None=>{l.push((*i,*w*lp));r.push((*i,*w*(1.0-lp)))}}}let wl:f64=l.iter().map(|x|x.1).sum();let wr:f64=r.iter().map(|x|x.1).sum();if wl+1e-12<min||wr+1e-12<min{continue}let gain=base-(wl/total)*gini(rows,&l)-(wr/total)*gini(rows,&r);let cand=(gain,names[f].clone(),t,f,lp);let take=match &best{None=>true,Some(b)=>gain>b.0+1e-12||((gain-b.0).abs()<=1e-12&&(names[f]<b.1||(names[f]==b.1&&t<b.2)))};if take{best=Some(cand)}}}
 let Some((gain,_,t,f,lp))=best else{return Node::Leaf(dist(rows,s))};if gain<=1e-15{return Node::Leaf(dist(rows,s))}let mut l=Vec::new();let mut r=Vec::new();for(i,w)in s{match rows[*i].x[f]{Some(v)if v<=t=>l.push((*i,*w)),Some(_)=>r.push((*i,*w)),None=>{l.push((*i,*w*lp));r.push((*i,*w*(1.0-lp)))}}}Node::Split{f,t,l:Box::new(build(rows,names,&l,dep+1,max,min)),r:Box::new(build(rows,names,&r,dep+1,max,min)),lp}}
fn predict(n:&Node,x:&[Option<f64>])->BTreeMap<String,f64>{match n{Node::Leaf(d)=>d.clone(),Node::Split{f,t,l,r,lp}=>match x[*f]{Some(v)=>predict(if v<=*t{l}else{r},x),None=>{let a=predict(l,x);let b=predict(r,x);let mut d=BTreeMap::new();for(k,v)in a{*d.entry(k).or_insert(0.0)+=v*lp}for(k,v)in b{*d.entry(k).or_insert(0.0)+=v*(1.0-lp)}d}}}}
RUST
rustc -O /app/task_file/src/main.rs -o /app/task_file/branch
