use time::{Duration, OffsetDateTime};

#[derive(Debug, Clone, Copy)]
struct WindowScenario {
    name: &'static str,
    start_epoch: i64,
    duration_seconds: i64,
    probe_offset: i64,
    expected: bool,
}

const WINDOW_SCENARIOS: [WindowScenario; 80] = [
    WindowScenario {
        name: "window-case-000",
        start_epoch: 1700000000,
        duration_seconds: 60,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-001",
        start_epoch: 1700000120,
        duration_seconds: 90,
        probe_offset: 89,
        expected: true,
    },
    WindowScenario {
        name: "window-case-002",
        start_epoch: 1700000240,
        duration_seconds: 120,
        probe_offset: 120,
        expected: false,
    },
    WindowScenario {
        name: "window-case-003",
        start_epoch: 1700000360,
        duration_seconds: 150,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-004",
        start_epoch: 1700000480,
        duration_seconds: 180,
        probe_offset: 179,
        expected: true,
    },
    WindowScenario {
        name: "window-case-005",
        start_epoch: 1700000600,
        duration_seconds: 210,
        probe_offset: 210,
        expected: false,
    },
    WindowScenario {
        name: "window-case-006",
        start_epoch: 1700000720,
        duration_seconds: 240,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-007",
        start_epoch: 1700000840,
        duration_seconds: 270,
        probe_offset: 269,
        expected: true,
    },
    WindowScenario {
        name: "window-case-008",
        start_epoch: 1700000960,
        duration_seconds: 300,
        probe_offset: 300,
        expected: false,
    },
    WindowScenario {
        name: "window-case-009",
        start_epoch: 1700001080,
        duration_seconds: 330,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-010",
        start_epoch: 1700001200,
        duration_seconds: 360,
        probe_offset: 359,
        expected: true,
    },
    WindowScenario {
        name: "window-case-011",
        start_epoch: 1700001320,
        duration_seconds: 390,
        probe_offset: 390,
        expected: false,
    },
    WindowScenario {
        name: "window-case-012",
        start_epoch: 1700001440,
        duration_seconds: 60,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-013",
        start_epoch: 1700001560,
        duration_seconds: 90,
        probe_offset: 89,
        expected: true,
    },
    WindowScenario {
        name: "window-case-014",
        start_epoch: 1700001680,
        duration_seconds: 120,
        probe_offset: 120,
        expected: false,
    },
    WindowScenario {
        name: "window-case-015",
        start_epoch: 1700001800,
        duration_seconds: 150,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-016",
        start_epoch: 1700001920,
        duration_seconds: 180,
        probe_offset: 179,
        expected: true,
    },
    WindowScenario {
        name: "window-case-017",
        start_epoch: 1700002040,
        duration_seconds: 210,
        probe_offset: 210,
        expected: false,
    },
    WindowScenario {
        name: "window-case-018",
        start_epoch: 1700002160,
        duration_seconds: 240,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-019",
        start_epoch: 1700002280,
        duration_seconds: 270,
        probe_offset: 269,
        expected: true,
    },
    WindowScenario {
        name: "window-case-020",
        start_epoch: 1700002400,
        duration_seconds: 300,
        probe_offset: 300,
        expected: false,
    },
    WindowScenario {
        name: "window-case-021",
        start_epoch: 1700002520,
        duration_seconds: 330,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-022",
        start_epoch: 1700002640,
        duration_seconds: 360,
        probe_offset: 359,
        expected: true,
    },
    WindowScenario {
        name: "window-case-023",
        start_epoch: 1700002760,
        duration_seconds: 390,
        probe_offset: 390,
        expected: false,
    },
    WindowScenario {
        name: "window-case-024",
        start_epoch: 1700002880,
        duration_seconds: 60,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-025",
        start_epoch: 1700003000,
        duration_seconds: 90,
        probe_offset: 89,
        expected: true,
    },
    WindowScenario {
        name: "window-case-026",
        start_epoch: 1700003120,
        duration_seconds: 120,
        probe_offset: 120,
        expected: false,
    },
    WindowScenario {
        name: "window-case-027",
        start_epoch: 1700003240,
        duration_seconds: 150,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-028",
        start_epoch: 1700003360,
        duration_seconds: 180,
        probe_offset: 179,
        expected: true,
    },
    WindowScenario {
        name: "window-case-029",
        start_epoch: 1700003480,
        duration_seconds: 210,
        probe_offset: 210,
        expected: false,
    },
    WindowScenario {
        name: "window-case-030",
        start_epoch: 1700003600,
        duration_seconds: 240,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-031",
        start_epoch: 1700003720,
        duration_seconds: 270,
        probe_offset: 269,
        expected: true,
    },
    WindowScenario {
        name: "window-case-032",
        start_epoch: 1700003840,
        duration_seconds: 300,
        probe_offset: 300,
        expected: false,
    },
    WindowScenario {
        name: "window-case-033",
        start_epoch: 1700003960,
        duration_seconds: 330,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-034",
        start_epoch: 1700004080,
        duration_seconds: 360,
        probe_offset: 359,
        expected: true,
    },
    WindowScenario {
        name: "window-case-035",
        start_epoch: 1700004200,
        duration_seconds: 390,
        probe_offset: 390,
        expected: false,
    },
    WindowScenario {
        name: "window-case-036",
        start_epoch: 1700004320,
        duration_seconds: 60,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-037",
        start_epoch: 1700004440,
        duration_seconds: 90,
        probe_offset: 89,
        expected: true,
    },
    WindowScenario {
        name: "window-case-038",
        start_epoch: 1700004560,
        duration_seconds: 120,
        probe_offset: 120,
        expected: false,
    },
    WindowScenario {
        name: "window-case-039",
        start_epoch: 1700004680,
        duration_seconds: 150,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-040",
        start_epoch: 1700004800,
        duration_seconds: 180,
        probe_offset: 179,
        expected: true,
    },
    WindowScenario {
        name: "window-case-041",
        start_epoch: 1700004920,
        duration_seconds: 210,
        probe_offset: 210,
        expected: false,
    },
    WindowScenario {
        name: "window-case-042",
        start_epoch: 1700005040,
        duration_seconds: 240,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-043",
        start_epoch: 1700005160,
        duration_seconds: 270,
        probe_offset: 269,
        expected: true,
    },
    WindowScenario {
        name: "window-case-044",
        start_epoch: 1700005280,
        duration_seconds: 300,
        probe_offset: 300,
        expected: false,
    },
    WindowScenario {
        name: "window-case-045",
        start_epoch: 1700005400,
        duration_seconds: 330,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-046",
        start_epoch: 1700005520,
        duration_seconds: 360,
        probe_offset: 359,
        expected: true,
    },
    WindowScenario {
        name: "window-case-047",
        start_epoch: 1700005640,
        duration_seconds: 390,
        probe_offset: 390,
        expected: false,
    },
    WindowScenario {
        name: "window-case-048",
        start_epoch: 1700005760,
        duration_seconds: 60,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-049",
        start_epoch: 1700005880,
        duration_seconds: 90,
        probe_offset: 89,
        expected: true,
    },
    WindowScenario {
        name: "window-case-050",
        start_epoch: 1700006000,
        duration_seconds: 120,
        probe_offset: 120,
        expected: false,
    },
    WindowScenario {
        name: "window-case-051",
        start_epoch: 1700006120,
        duration_seconds: 150,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-052",
        start_epoch: 1700006240,
        duration_seconds: 180,
        probe_offset: 179,
        expected: true,
    },
    WindowScenario {
        name: "window-case-053",
        start_epoch: 1700006360,
        duration_seconds: 210,
        probe_offset: 210,
        expected: false,
    },
    WindowScenario {
        name: "window-case-054",
        start_epoch: 1700006480,
        duration_seconds: 240,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-055",
        start_epoch: 1700006600,
        duration_seconds: 270,
        probe_offset: 269,
        expected: true,
    },
    WindowScenario {
        name: "window-case-056",
        start_epoch: 1700006720,
        duration_seconds: 300,
        probe_offset: 300,
        expected: false,
    },
    WindowScenario {
        name: "window-case-057",
        start_epoch: 1700006840,
        duration_seconds: 330,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-058",
        start_epoch: 1700006960,
        duration_seconds: 360,
        probe_offset: 359,
        expected: true,
    },
    WindowScenario {
        name: "window-case-059",
        start_epoch: 1700007080,
        duration_seconds: 390,
        probe_offset: 390,
        expected: false,
    },
    WindowScenario {
        name: "window-case-060",
        start_epoch: 1700007200,
        duration_seconds: 60,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-061",
        start_epoch: 1700007320,
        duration_seconds: 90,
        probe_offset: 89,
        expected: true,
    },
    WindowScenario {
        name: "window-case-062",
        start_epoch: 1700007440,
        duration_seconds: 120,
        probe_offset: 120,
        expected: false,
    },
    WindowScenario {
        name: "window-case-063",
        start_epoch: 1700007560,
        duration_seconds: 150,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-064",
        start_epoch: 1700007680,
        duration_seconds: 180,
        probe_offset: 179,
        expected: true,
    },
    WindowScenario {
        name: "window-case-065",
        start_epoch: 1700007800,
        duration_seconds: 210,
        probe_offset: 210,
        expected: false,
    },
    WindowScenario {
        name: "window-case-066",
        start_epoch: 1700007920,
        duration_seconds: 240,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-067",
        start_epoch: 1700008040,
        duration_seconds: 270,
        probe_offset: 269,
        expected: true,
    },
    WindowScenario {
        name: "window-case-068",
        start_epoch: 1700008160,
        duration_seconds: 300,
        probe_offset: 300,
        expected: false,
    },
    WindowScenario {
        name: "window-case-069",
        start_epoch: 1700008280,
        duration_seconds: 330,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-070",
        start_epoch: 1700008400,
        duration_seconds: 360,
        probe_offset: 359,
        expected: true,
    },
    WindowScenario {
        name: "window-case-071",
        start_epoch: 1700008520,
        duration_seconds: 390,
        probe_offset: 390,
        expected: false,
    },
    WindowScenario {
        name: "window-case-072",
        start_epoch: 1700008640,
        duration_seconds: 60,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-073",
        start_epoch: 1700008760,
        duration_seconds: 90,
        probe_offset: 89,
        expected: true,
    },
    WindowScenario {
        name: "window-case-074",
        start_epoch: 1700008880,
        duration_seconds: 120,
        probe_offset: 120,
        expected: false,
    },
    WindowScenario {
        name: "window-case-075",
        start_epoch: 1700009000,
        duration_seconds: 150,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-076",
        start_epoch: 1700009120,
        duration_seconds: 180,
        probe_offset: 179,
        expected: true,
    },
    WindowScenario {
        name: "window-case-077",
        start_epoch: 1700009240,
        duration_seconds: 210,
        probe_offset: 210,
        expected: false,
    },
    WindowScenario {
        name: "window-case-078",
        start_epoch: 1700009360,
        duration_seconds: 240,
        probe_offset: -1,
        expected: false,
    },
    WindowScenario {
        name: "window-case-079",
        start_epoch: 1700009480,
        duration_seconds: 270,
        probe_offset: 269,
        expected: true,
    },
];

#[test]
fn window_scenario_matrix_keeps_both_boundaries_explicit() {
    for scenario in WINDOW_SCENARIOS {
        let start = OffsetDateTime::from_unix_timestamp(scenario.start_epoch).unwrap();
        let window = crate::ReleaseWindow::new(
            start,
            Duration::seconds(scenario.duration_seconds),
        )
        .unwrap();
        let probe = start + Duration::seconds(scenario.probe_offset);
        assert_eq!(window.contains(probe), scenario.expected, "{}", scenario.name);
    }
}
