use domain_model::{AdvisoryFinding, DependencyChange};
use semver::Version;

#[derive(Debug, Clone, Copy)]
struct EnvelopeScenario {
    portfolio: &'static str,
    findings: usize,
    changes: usize,
    installed_patch: u64,
    selected_patch: u64,
}

const ENVELOPE_SCENARIOS: [EnvelopeScenario; 80] = [
    EnvelopeScenario {
        portfolio: "release-ring-000",
        findings: 0,
        changes: 0,
        installed_patch: 0,
        selected_patch: 1,
    },
    EnvelopeScenario {
        portfolio: "release-ring-001",
        findings: 1,
        changes: 1,
        installed_patch: 1,
        selected_patch: 2,
    },
    EnvelopeScenario {
        portfolio: "release-ring-002",
        findings: 2,
        changes: 2,
        installed_patch: 2,
        selected_patch: 3,
    },
    EnvelopeScenario {
        portfolio: "release-ring-003",
        findings: 3,
        changes: 3,
        installed_patch: 3,
        selected_patch: 4,
    },
    EnvelopeScenario {
        portfolio: "release-ring-004",
        findings: 4,
        changes: 0,
        installed_patch: 4,
        selected_patch: 5,
    },
    EnvelopeScenario {
        portfolio: "release-ring-005",
        findings: 0,
        changes: 1,
        installed_patch: 5,
        selected_patch: 6,
    },
    EnvelopeScenario {
        portfolio: "release-ring-006",
        findings: 1,
        changes: 2,
        installed_patch: 6,
        selected_patch: 7,
    },
    EnvelopeScenario {
        portfolio: "release-ring-007",
        findings: 2,
        changes: 3,
        installed_patch: 7,
        selected_patch: 8,
    },
    EnvelopeScenario {
        portfolio: "release-ring-008",
        findings: 3,
        changes: 0,
        installed_patch: 8,
        selected_patch: 9,
    },
    EnvelopeScenario {
        portfolio: "release-ring-009",
        findings: 4,
        changes: 1,
        installed_patch: 0,
        selected_patch: 1,
    },
    EnvelopeScenario {
        portfolio: "release-ring-010",
        findings: 0,
        changes: 2,
        installed_patch: 1,
        selected_patch: 2,
    },
    EnvelopeScenario {
        portfolio: "release-ring-011",
        findings: 1,
        changes: 3,
        installed_patch: 2,
        selected_patch: 3,
    },
    EnvelopeScenario {
        portfolio: "release-ring-012",
        findings: 2,
        changes: 0,
        installed_patch: 3,
        selected_patch: 4,
    },
    EnvelopeScenario {
        portfolio: "release-ring-013",
        findings: 3,
        changes: 1,
        installed_patch: 4,
        selected_patch: 5,
    },
    EnvelopeScenario {
        portfolio: "release-ring-014",
        findings: 4,
        changes: 2,
        installed_patch: 5,
        selected_patch: 6,
    },
    EnvelopeScenario {
        portfolio: "release-ring-015",
        findings: 0,
        changes: 3,
        installed_patch: 6,
        selected_patch: 7,
    },
    EnvelopeScenario {
        portfolio: "release-ring-016",
        findings: 1,
        changes: 0,
        installed_patch: 7,
        selected_patch: 8,
    },
    EnvelopeScenario {
        portfolio: "release-ring-017",
        findings: 2,
        changes: 1,
        installed_patch: 8,
        selected_patch: 9,
    },
    EnvelopeScenario {
        portfolio: "release-ring-018",
        findings: 3,
        changes: 2,
        installed_patch: 0,
        selected_patch: 1,
    },
    EnvelopeScenario {
        portfolio: "release-ring-019",
        findings: 4,
        changes: 3,
        installed_patch: 1,
        selected_patch: 2,
    },
    EnvelopeScenario {
        portfolio: "release-ring-020",
        findings: 0,
        changes: 0,
        installed_patch: 2,
        selected_patch: 3,
    },
    EnvelopeScenario {
        portfolio: "release-ring-021",
        findings: 1,
        changes: 1,
        installed_patch: 3,
        selected_patch: 4,
    },
    EnvelopeScenario {
        portfolio: "release-ring-022",
        findings: 2,
        changes: 2,
        installed_patch: 4,
        selected_patch: 5,
    },
    EnvelopeScenario {
        portfolio: "release-ring-023",
        findings: 3,
        changes: 3,
        installed_patch: 5,
        selected_patch: 6,
    },
    EnvelopeScenario {
        portfolio: "release-ring-024",
        findings: 4,
        changes: 0,
        installed_patch: 6,
        selected_patch: 7,
    },
    EnvelopeScenario {
        portfolio: "release-ring-025",
        findings: 0,
        changes: 1,
        installed_patch: 7,
        selected_patch: 8,
    },
    EnvelopeScenario {
        portfolio: "release-ring-026",
        findings: 1,
        changes: 2,
        installed_patch: 8,
        selected_patch: 9,
    },
    EnvelopeScenario {
        portfolio: "release-ring-027",
        findings: 2,
        changes: 3,
        installed_patch: 0,
        selected_patch: 1,
    },
    EnvelopeScenario {
        portfolio: "release-ring-028",
        findings: 3,
        changes: 0,
        installed_patch: 1,
        selected_patch: 2,
    },
    EnvelopeScenario {
        portfolio: "release-ring-029",
        findings: 4,
        changes: 1,
        installed_patch: 2,
        selected_patch: 3,
    },
    EnvelopeScenario {
        portfolio: "release-ring-030",
        findings: 0,
        changes: 2,
        installed_patch: 3,
        selected_patch: 4,
    },
    EnvelopeScenario {
        portfolio: "release-ring-031",
        findings: 1,
        changes: 3,
        installed_patch: 4,
        selected_patch: 5,
    },
    EnvelopeScenario {
        portfolio: "release-ring-032",
        findings: 2,
        changes: 0,
        installed_patch: 5,
        selected_patch: 6,
    },
    EnvelopeScenario {
        portfolio: "release-ring-033",
        findings: 3,
        changes: 1,
        installed_patch: 6,
        selected_patch: 7,
    },
    EnvelopeScenario {
        portfolio: "release-ring-034",
        findings: 4,
        changes: 2,
        installed_patch: 7,
        selected_patch: 8,
    },
    EnvelopeScenario {
        portfolio: "release-ring-035",
        findings: 0,
        changes: 3,
        installed_patch: 8,
        selected_patch: 9,
    },
    EnvelopeScenario {
        portfolio: "release-ring-036",
        findings: 1,
        changes: 0,
        installed_patch: 0,
        selected_patch: 1,
    },
    EnvelopeScenario {
        portfolio: "release-ring-037",
        findings: 2,
        changes: 1,
        installed_patch: 1,
        selected_patch: 2,
    },
    EnvelopeScenario {
        portfolio: "release-ring-038",
        findings: 3,
        changes: 2,
        installed_patch: 2,
        selected_patch: 3,
    },
    EnvelopeScenario {
        portfolio: "release-ring-039",
        findings: 4,
        changes: 3,
        installed_patch: 3,
        selected_patch: 4,
    },
    EnvelopeScenario {
        portfolio: "release-ring-040",
        findings: 0,
        changes: 0,
        installed_patch: 4,
        selected_patch: 5,
    },
    EnvelopeScenario {
        portfolio: "release-ring-041",
        findings: 1,
        changes: 1,
        installed_patch: 5,
        selected_patch: 6,
    },
    EnvelopeScenario {
        portfolio: "release-ring-042",
        findings: 2,
        changes: 2,
        installed_patch: 6,
        selected_patch: 7,
    },
    EnvelopeScenario {
        portfolio: "release-ring-043",
        findings: 3,
        changes: 3,
        installed_patch: 7,
        selected_patch: 8,
    },
    EnvelopeScenario {
        portfolio: "release-ring-044",
        findings: 4,
        changes: 0,
        installed_patch: 8,
        selected_patch: 9,
    },
    EnvelopeScenario {
        portfolio: "release-ring-045",
        findings: 0,
        changes: 1,
        installed_patch: 0,
        selected_patch: 1,
    },
    EnvelopeScenario {
        portfolio: "release-ring-046",
        findings: 1,
        changes: 2,
        installed_patch: 1,
        selected_patch: 2,
    },
    EnvelopeScenario {
        portfolio: "release-ring-047",
        findings: 2,
        changes: 3,
        installed_patch: 2,
        selected_patch: 3,
    },
    EnvelopeScenario {
        portfolio: "release-ring-048",
        findings: 3,
        changes: 0,
        installed_patch: 3,
        selected_patch: 4,
    },
    EnvelopeScenario {
        portfolio: "release-ring-049",
        findings: 4,
        changes: 1,
        installed_patch: 4,
        selected_patch: 5,
    },
    EnvelopeScenario {
        portfolio: "release-ring-050",
        findings: 0,
        changes: 2,
        installed_patch: 5,
        selected_patch: 6,
    },
    EnvelopeScenario {
        portfolio: "release-ring-051",
        findings: 1,
        changes: 3,
        installed_patch: 6,
        selected_patch: 7,
    },
    EnvelopeScenario {
        portfolio: "release-ring-052",
        findings: 2,
        changes: 0,
        installed_patch: 7,
        selected_patch: 8,
    },
    EnvelopeScenario {
        portfolio: "release-ring-053",
        findings: 3,
        changes: 1,
        installed_patch: 8,
        selected_patch: 9,
    },
    EnvelopeScenario {
        portfolio: "release-ring-054",
        findings: 4,
        changes: 2,
        installed_patch: 0,
        selected_patch: 1,
    },
    EnvelopeScenario {
        portfolio: "release-ring-055",
        findings: 0,
        changes: 3,
        installed_patch: 1,
        selected_patch: 2,
    },
    EnvelopeScenario {
        portfolio: "release-ring-056",
        findings: 1,
        changes: 0,
        installed_patch: 2,
        selected_patch: 3,
    },
    EnvelopeScenario {
        portfolio: "release-ring-057",
        findings: 2,
        changes: 1,
        installed_patch: 3,
        selected_patch: 4,
    },
    EnvelopeScenario {
        portfolio: "release-ring-058",
        findings: 3,
        changes: 2,
        installed_patch: 4,
        selected_patch: 5,
    },
    EnvelopeScenario {
        portfolio: "release-ring-059",
        findings: 4,
        changes: 3,
        installed_patch: 5,
        selected_patch: 6,
    },
    EnvelopeScenario {
        portfolio: "release-ring-060",
        findings: 0,
        changes: 0,
        installed_patch: 6,
        selected_patch: 7,
    },
    EnvelopeScenario {
        portfolio: "release-ring-061",
        findings: 1,
        changes: 1,
        installed_patch: 7,
        selected_patch: 8,
    },
    EnvelopeScenario {
        portfolio: "release-ring-062",
        findings: 2,
        changes: 2,
        installed_patch: 8,
        selected_patch: 9,
    },
    EnvelopeScenario {
        portfolio: "release-ring-063",
        findings: 3,
        changes: 3,
        installed_patch: 0,
        selected_patch: 1,
    },
    EnvelopeScenario {
        portfolio: "release-ring-064",
        findings: 4,
        changes: 0,
        installed_patch: 1,
        selected_patch: 2,
    },
    EnvelopeScenario {
        portfolio: "release-ring-065",
        findings: 0,
        changes: 1,
        installed_patch: 2,
        selected_patch: 3,
    },
    EnvelopeScenario {
        portfolio: "release-ring-066",
        findings: 1,
        changes: 2,
        installed_patch: 3,
        selected_patch: 4,
    },
    EnvelopeScenario {
        portfolio: "release-ring-067",
        findings: 2,
        changes: 3,
        installed_patch: 4,
        selected_patch: 5,
    },
    EnvelopeScenario {
        portfolio: "release-ring-068",
        findings: 3,
        changes: 0,
        installed_patch: 5,
        selected_patch: 6,
    },
    EnvelopeScenario {
        portfolio: "release-ring-069",
        findings: 4,
        changes: 1,
        installed_patch: 6,
        selected_patch: 7,
    },
    EnvelopeScenario {
        portfolio: "release-ring-070",
        findings: 0,
        changes: 2,
        installed_patch: 7,
        selected_patch: 8,
    },
    EnvelopeScenario {
        portfolio: "release-ring-071",
        findings: 1,
        changes: 3,
        installed_patch: 8,
        selected_patch: 9,
    },
    EnvelopeScenario {
        portfolio: "release-ring-072",
        findings: 2,
        changes: 0,
        installed_patch: 0,
        selected_patch: 1,
    },
    EnvelopeScenario {
        portfolio: "release-ring-073",
        findings: 3,
        changes: 1,
        installed_patch: 1,
        selected_patch: 2,
    },
    EnvelopeScenario {
        portfolio: "release-ring-074",
        findings: 4,
        changes: 2,
        installed_patch: 2,
        selected_patch: 3,
    },
    EnvelopeScenario {
        portfolio: "release-ring-075",
        findings: 0,
        changes: 3,
        installed_patch: 3,
        selected_patch: 4,
    },
    EnvelopeScenario {
        portfolio: "release-ring-076",
        findings: 1,
        changes: 0,
        installed_patch: 4,
        selected_patch: 5,
    },
    EnvelopeScenario {
        portfolio: "release-ring-077",
        findings: 2,
        changes: 1,
        installed_patch: 5,
        selected_patch: 6,
    },
    EnvelopeScenario {
        portfolio: "release-ring-078",
        findings: 3,
        changes: 2,
        installed_patch: 6,
        selected_patch: 7,
    },
    EnvelopeScenario {
        portfolio: "release-ring-079",
        findings: 4,
        changes: 3,
        installed_patch: 7,
        selected_patch: 8,
    },
];

#[test]
fn envelope_scenario_matrix_round_trips_each_release_shape() {
    for scenario in ENVELOPE_SCENARIOS {
        let findings = (0..scenario.findings)
            .map(|index| AdvisoryFinding {
                id: format!("RUSTSEC-TEST-{index:04}"),
                package: format!("crate-{index}"),
                installed: Version::new(1, 0, scenario.installed_patch),
                fixed: Some(Version::new(1, 0, scenario.selected_patch)),
            })
            .collect();
        let changes = (0..scenario.changes)
            .map(|index| DependencyChange {
                package: format!("crate-{index}"),
                previous: Version::new(1, 0, scenario.installed_patch),
                selected: Version::new(1, 0, scenario.selected_patch),
                reason: "fixture boundary".to_owned(),
            })
            .collect();
        let envelope = crate::AuditEnvelope {
            portfolio: scenario.portfolio.to_owned(),
            findings,
            changes,
        };
        let encoded = crate::encode(&envelope).unwrap();
        assert_eq!(crate::decode(&encoded).unwrap(), envelope);
    }
}
