#[derive(Debug, Clone, Copy)]
struct VersionScenario {
    package: &'static str,
    previous: (u64, u64, u64),
    selected: (u64, u64, u64),
    reason: &'static str,
}

const VERSION_SCENARIOS: [VersionScenario; 80] = [
    VersionScenario {
        package: "alpha-index-000",
        previous: (1, 0, 0),
        selected: (1, 0, 1),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "beta-wire-001",
        previous: (2, 0, 1),
        selected: (2, 0, 2),
        reason: "yanked release",
    },
    VersionScenario {
        package: "clock-cache-002",
        previous: (3, 0, 2),
        selected: (3, 0, 3),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "delta-codec-003",
        previous: (1, 1, 3),
        selected: (1, 1, 4),
        reason: "registry policy",
    },
    VersionScenario {
        package: "event-ring-004",
        previous: (2, 1, 4),
        selected: (2, 1, 5),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "ledger-view-005",
        previous: (3, 1, 5),
        selected: (3, 1, 6),
        reason: "yanked release",
    },
    VersionScenario {
        package: "policy-set-006",
        previous: (1, 2, 6),
        selected: (1, 2, 7),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "queue-slot-007",
        previous: (2, 2, 0),
        selected: (2, 2, 1),
        reason: "registry policy",
    },
    VersionScenario {
        package: "alpha-index-008",
        previous: (3, 2, 1),
        selected: (3, 2, 2),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "beta-wire-009",
        previous: (1, 3, 2),
        selected: (1, 3, 3),
        reason: "yanked release",
    },
    VersionScenario {
        package: "clock-cache-010",
        previous: (2, 3, 3),
        selected: (2, 3, 4),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "delta-codec-011",
        previous: (3, 3, 4),
        selected: (3, 3, 5),
        reason: "registry policy",
    },
    VersionScenario {
        package: "event-ring-012",
        previous: (1, 4, 5),
        selected: (1, 4, 6),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "ledger-view-013",
        previous: (2, 4, 6),
        selected: (2, 4, 7),
        reason: "yanked release",
    },
    VersionScenario {
        package: "policy-set-014",
        previous: (3, 4, 0),
        selected: (3, 4, 1),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "queue-slot-015",
        previous: (1, 5, 1),
        selected: (1, 5, 2),
        reason: "registry policy",
    },
    VersionScenario {
        package: "alpha-index-016",
        previous: (2, 5, 2),
        selected: (2, 5, 3),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "beta-wire-017",
        previous: (3, 5, 3),
        selected: (3, 5, 4),
        reason: "yanked release",
    },
    VersionScenario {
        package: "clock-cache-018",
        previous: (1, 6, 4),
        selected: (1, 6, 5),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "delta-codec-019",
        previous: (2, 6, 5),
        selected: (2, 6, 6),
        reason: "registry policy",
    },
    VersionScenario {
        package: "event-ring-020",
        previous: (3, 6, 6),
        selected: (3, 6, 7),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "ledger-view-021",
        previous: (1, 7, 0),
        selected: (1, 7, 1),
        reason: "yanked release",
    },
    VersionScenario {
        package: "policy-set-022",
        previous: (2, 7, 1),
        selected: (2, 7, 2),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "queue-slot-023",
        previous: (3, 7, 2),
        selected: (3, 7, 3),
        reason: "registry policy",
    },
    VersionScenario {
        package: "alpha-index-024",
        previous: (1, 8, 3),
        selected: (1, 8, 4),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "beta-wire-025",
        previous: (2, 8, 4),
        selected: (2, 8, 5),
        reason: "yanked release",
    },
    VersionScenario {
        package: "clock-cache-026",
        previous: (3, 8, 5),
        selected: (3, 8, 6),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "delta-codec-027",
        previous: (1, 9, 6),
        selected: (1, 9, 7),
        reason: "registry policy",
    },
    VersionScenario {
        package: "event-ring-028",
        previous: (2, 9, 0),
        selected: (2, 9, 1),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "ledger-view-029",
        previous: (3, 9, 1),
        selected: (3, 9, 2),
        reason: "yanked release",
    },
    VersionScenario {
        package: "policy-set-030",
        previous: (1, 0, 2),
        selected: (1, 0, 3),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "queue-slot-031",
        previous: (2, 0, 3),
        selected: (2, 0, 4),
        reason: "registry policy",
    },
    VersionScenario {
        package: "alpha-index-032",
        previous: (3, 0, 4),
        selected: (3, 0, 5),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "beta-wire-033",
        previous: (1, 1, 5),
        selected: (1, 1, 6),
        reason: "yanked release",
    },
    VersionScenario {
        package: "clock-cache-034",
        previous: (2, 1, 6),
        selected: (2, 1, 7),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "delta-codec-035",
        previous: (3, 1, 0),
        selected: (3, 1, 1),
        reason: "registry policy",
    },
    VersionScenario {
        package: "event-ring-036",
        previous: (1, 2, 1),
        selected: (1, 2, 2),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "ledger-view-037",
        previous: (2, 2, 2),
        selected: (2, 2, 3),
        reason: "yanked release",
    },
    VersionScenario {
        package: "policy-set-038",
        previous: (3, 2, 3),
        selected: (3, 2, 4),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "queue-slot-039",
        previous: (1, 3, 4),
        selected: (1, 3, 5),
        reason: "registry policy",
    },
    VersionScenario {
        package: "alpha-index-040",
        previous: (2, 3, 5),
        selected: (2, 3, 6),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "beta-wire-041",
        previous: (3, 3, 6),
        selected: (3, 3, 7),
        reason: "yanked release",
    },
    VersionScenario {
        package: "clock-cache-042",
        previous: (1, 4, 0),
        selected: (1, 4, 1),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "delta-codec-043",
        previous: (2, 4, 1),
        selected: (2, 4, 2),
        reason: "registry policy",
    },
    VersionScenario {
        package: "event-ring-044",
        previous: (3, 4, 2),
        selected: (3, 4, 3),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "ledger-view-045",
        previous: (1, 5, 3),
        selected: (1, 5, 4),
        reason: "yanked release",
    },
    VersionScenario {
        package: "policy-set-046",
        previous: (2, 5, 4),
        selected: (2, 5, 5),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "queue-slot-047",
        previous: (3, 5, 5),
        selected: (3, 5, 6),
        reason: "registry policy",
    },
    VersionScenario {
        package: "alpha-index-048",
        previous: (1, 6, 6),
        selected: (1, 6, 7),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "beta-wire-049",
        previous: (2, 6, 0),
        selected: (2, 6, 1),
        reason: "yanked release",
    },
    VersionScenario {
        package: "clock-cache-050",
        previous: (3, 6, 1),
        selected: (3, 6, 2),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "delta-codec-051",
        previous: (1, 7, 2),
        selected: (1, 7, 3),
        reason: "registry policy",
    },
    VersionScenario {
        package: "event-ring-052",
        previous: (2, 7, 3),
        selected: (2, 7, 4),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "ledger-view-053",
        previous: (3, 7, 4),
        selected: (3, 7, 5),
        reason: "yanked release",
    },
    VersionScenario {
        package: "policy-set-054",
        previous: (1, 8, 5),
        selected: (1, 8, 6),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "queue-slot-055",
        previous: (2, 8, 6),
        selected: (2, 8, 7),
        reason: "registry policy",
    },
    VersionScenario {
        package: "alpha-index-056",
        previous: (3, 8, 0),
        selected: (3, 8, 1),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "beta-wire-057",
        previous: (1, 9, 1),
        selected: (1, 9, 2),
        reason: "yanked release",
    },
    VersionScenario {
        package: "clock-cache-058",
        previous: (2, 9, 2),
        selected: (2, 9, 3),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "delta-codec-059",
        previous: (3, 9, 3),
        selected: (3, 9, 4),
        reason: "registry policy",
    },
    VersionScenario {
        package: "event-ring-060",
        previous: (1, 0, 4),
        selected: (1, 0, 5),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "ledger-view-061",
        previous: (2, 0, 5),
        selected: (2, 0, 6),
        reason: "yanked release",
    },
    VersionScenario {
        package: "policy-set-062",
        previous: (3, 0, 6),
        selected: (3, 0, 7),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "queue-slot-063",
        previous: (1, 1, 0),
        selected: (1, 1, 1),
        reason: "registry policy",
    },
    VersionScenario {
        package: "alpha-index-064",
        previous: (2, 1, 1),
        selected: (2, 1, 2),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "beta-wire-065",
        previous: (3, 1, 2),
        selected: (3, 1, 3),
        reason: "yanked release",
    },
    VersionScenario {
        package: "clock-cache-066",
        previous: (1, 2, 3),
        selected: (1, 2, 4),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "delta-codec-067",
        previous: (2, 2, 4),
        selected: (2, 2, 5),
        reason: "registry policy",
    },
    VersionScenario {
        package: "event-ring-068",
        previous: (3, 2, 5),
        selected: (3, 2, 6),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "ledger-view-069",
        previous: (1, 3, 6),
        selected: (1, 3, 7),
        reason: "yanked release",
    },
    VersionScenario {
        package: "policy-set-070",
        previous: (2, 3, 0),
        selected: (2, 3, 1),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "queue-slot-071",
        previous: (3, 3, 1),
        selected: (3, 3, 2),
        reason: "registry policy",
    },
    VersionScenario {
        package: "alpha-index-072",
        previous: (1, 4, 2),
        selected: (1, 4, 3),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "beta-wire-073",
        previous: (2, 4, 3),
        selected: (2, 4, 4),
        reason: "yanked release",
    },
    VersionScenario {
        package: "clock-cache-074",
        previous: (3, 4, 4),
        selected: (3, 4, 5),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "delta-codec-075",
        previous: (1, 5, 5),
        selected: (1, 5, 6),
        reason: "registry policy",
    },
    VersionScenario {
        package: "event-ring-076",
        previous: (2, 5, 6),
        selected: (2, 5, 7),
        reason: "advisory boundary",
    },
    VersionScenario {
        package: "ledger-view-077",
        previous: (3, 5, 0),
        selected: (3, 5, 1),
        reason: "yanked release",
    },
    VersionScenario {
        package: "policy-set-078",
        previous: (1, 6, 1),
        selected: (1, 6, 2),
        reason: "toolchain floor",
    },
    VersionScenario {
        package: "queue-slot-079",
        previous: (2, 6, 2),
        selected: (2, 6, 3),
        reason: "registry policy",
    },
];

#[test]
fn version_scenario_matrix_has_ordered_release_moves() {
    use semver::Version;

    for scenario in VERSION_SCENARIOS {
        let previous = Version::new(scenario.previous.0, scenario.previous.1, scenario.previous.2);
        let selected = Version::new(scenario.selected.0, scenario.selected.1, scenario.selected.2);
        let change = crate::DependencyChange {
            package: scenario.package.to_owned(),
            previous,
            selected,
            reason: scenario.reason.to_owned(),
        };
        assert!(change.is_upgrade(), "{}", scenario.package);
        assert!(!change.reason.is_empty());
    }
}
