source "https://rubygems.org"

gem "rails", "7.2.2"
gem "puma", "6.4.3"
gem "psych", "~> 5.1"
gem "jwt", "2.8.2"

group :development, :test do
  gem "rspec-rails", "6.1.5"
  gem "rack-test", "2.1.0"
end
