use std::collections::BTreeSet;

use domain_model::DependencyChange;
use semver::Version;

#[derive(Debug, Clone, Copy)]
struct FingerprintScenario {
    portfolio: &'static str,
    package: &'static str,
    previous: (u64, u64, u64),
    selected: (u64, u64, u64),
    reason: &'static str,
    ordinal: u32,
}

const FINGERPRINT_SCENARIOS: [FingerprintScenario; 80] = [
    FingerprintScenario {
        portfolio: "stable-0",
        package: "release-crate-000",
        previous: (1, 0, 0),
        selected: (1, 0, 1),
        reason: "rustsec boundary",
        ordinal: 1,
    },
    FingerprintScenario {
        portfolio: "candidate-0",
        package: "release-crate-001",
        previous: (1, 1, 1),
        selected: (1, 1, 2),
        reason: "yanked index row",
        ordinal: 2,
    },
    FingerprintScenario {
        portfolio: "nightly-0",
        package: "release-crate-002",
        previous: (1, 2, 2),
        selected: (1, 2, 3),
        reason: "toolchain floor",
        ordinal: 3,
    },
    FingerprintScenario {
        portfolio: "emergency-0",
        package: "release-crate-003",
        previous: (1, 3, 3),
        selected: (1, 3, 4),
        reason: "source policy",
        ordinal: 4,
    },
    FingerprintScenario {
        portfolio: "maintenance-0",
        package: "release-crate-004",
        previous: (1, 4, 4),
        selected: (1, 4, 5),
        reason: "rustsec boundary",
        ordinal: 5,
    },
    FingerprintScenario {
        portfolio: "stable-1",
        package: "release-crate-005",
        previous: (1, 5, 5),
        selected: (1, 5, 6),
        reason: "yanked index row",
        ordinal: 6,
    },
    FingerprintScenario {
        portfolio: "candidate-1",
        package: "release-crate-006",
        previous: (1, 6, 6),
        selected: (1, 6, 7),
        reason: "toolchain floor",
        ordinal: 7,
    },
    FingerprintScenario {
        portfolio: "nightly-1",
        package: "release-crate-007",
        previous: (1, 7, 0),
        selected: (1, 7, 1),
        reason: "source policy",
        ordinal: 8,
    },
    FingerprintScenario {
        portfolio: "emergency-1",
        package: "release-crate-008",
        previous: (1, 8, 1),
        selected: (1, 8, 2),
        reason: "rustsec boundary",
        ordinal: 9,
    },
    FingerprintScenario {
        portfolio: "maintenance-1",
        package: "release-crate-009",
        previous: (1, 0, 2),
        selected: (1, 0, 3),
        reason: "yanked index row",
        ordinal: 10,
    },
    FingerprintScenario {
        portfolio: "stable-2",
        package: "release-crate-010",
        previous: (1, 1, 3),
        selected: (1, 1, 4),
        reason: "toolchain floor",
        ordinal: 11,
    },
    FingerprintScenario {
        portfolio: "candidate-2",
        package: "release-crate-011",
        previous: (1, 2, 4),
        selected: (1, 2, 5),
        reason: "source policy",
        ordinal: 12,
    },
    FingerprintScenario {
        portfolio: "nightly-2",
        package: "release-crate-012",
        previous: (1, 3, 5),
        selected: (1, 3, 6),
        reason: "rustsec boundary",
        ordinal: 13,
    },
    FingerprintScenario {
        portfolio: "emergency-2",
        package: "release-crate-013",
        previous: (1, 4, 6),
        selected: (1, 4, 7),
        reason: "yanked index row",
        ordinal: 14,
    },
    FingerprintScenario {
        portfolio: "maintenance-2",
        package: "release-crate-014",
        previous: (1, 5, 0),
        selected: (1, 5, 1),
        reason: "toolchain floor",
        ordinal: 15,
    },
    FingerprintScenario {
        portfolio: "stable-3",
        package: "release-crate-015",
        previous: (1, 6, 1),
        selected: (1, 6, 2),
        reason: "source policy",
        ordinal: 16,
    },
    FingerprintScenario {
        portfolio: "candidate-3",
        package: "release-crate-016",
        previous: (1, 7, 2),
        selected: (1, 7, 3),
        reason: "rustsec boundary",
        ordinal: 17,
    },
    FingerprintScenario {
        portfolio: "nightly-3",
        package: "release-crate-017",
        previous: (1, 8, 3),
        selected: (1, 8, 4),
        reason: "yanked index row",
        ordinal: 18,
    },
    FingerprintScenario {
        portfolio: "emergency-3",
        package: "release-crate-018",
        previous: (1, 0, 4),
        selected: (1, 0, 5),
        reason: "toolchain floor",
        ordinal: 19,
    },
    FingerprintScenario {
        portfolio: "maintenance-3",
        package: "release-crate-019",
        previous: (1, 1, 5),
        selected: (1, 1, 6),
        reason: "source policy",
        ordinal: 20,
    },
    FingerprintScenario {
        portfolio: "stable-4",
        package: "release-crate-020",
        previous: (1, 2, 6),
        selected: (1, 2, 7),
        reason: "rustsec boundary",
        ordinal: 21,
    },
    FingerprintScenario {
        portfolio: "candidate-4",
        package: "release-crate-021",
        previous: (1, 3, 0),
        selected: (1, 3, 1),
        reason: "yanked index row",
        ordinal: 22,
    },
    FingerprintScenario {
        portfolio: "nightly-4",
        package: "release-crate-022",
        previous: (1, 4, 1),
        selected: (1, 4, 2),
        reason: "toolchain floor",
        ordinal: 23,
    },
    FingerprintScenario {
        portfolio: "emergency-4",
        package: "release-crate-023",
        previous: (1, 5, 2),
        selected: (1, 5, 3),
        reason: "source policy",
        ordinal: 24,
    },
    FingerprintScenario {
        portfolio: "maintenance-4",
        package: "release-crate-024",
        previous: (1, 6, 3),
        selected: (1, 6, 4),
        reason: "rustsec boundary",
        ordinal: 25,
    },
    FingerprintScenario {
        portfolio: "stable-5",
        package: "release-crate-025",
        previous: (1, 7, 4),
        selected: (1, 7, 5),
        reason: "yanked index row",
        ordinal: 26,
    },
    FingerprintScenario {
        portfolio: "candidate-5",
        package: "release-crate-026",
        previous: (1, 8, 5),
        selected: (1, 8, 6),
        reason: "toolchain floor",
        ordinal: 27,
    },
    FingerprintScenario {
        portfolio: "nightly-5",
        package: "release-crate-027",
        previous: (1, 0, 6),
        selected: (1, 0, 7),
        reason: "source policy",
        ordinal: 28,
    },
    FingerprintScenario {
        portfolio: "emergency-5",
        package: "release-crate-028",
        previous: (1, 1, 0),
        selected: (1, 1, 1),
        reason: "rustsec boundary",
        ordinal: 29,
    },
    FingerprintScenario {
        portfolio: "maintenance-5",
        package: "release-crate-029",
        previous: (1, 2, 1),
        selected: (1, 2, 2),
        reason: "yanked index row",
        ordinal: 30,
    },
    FingerprintScenario {
        portfolio: "stable-6",
        package: "release-crate-030",
        previous: (1, 3, 2),
        selected: (1, 3, 3),
        reason: "toolchain floor",
        ordinal: 31,
    },
    FingerprintScenario {
        portfolio: "candidate-6",
        package: "release-crate-031",
        previous: (1, 4, 3),
        selected: (1, 4, 4),
        reason: "source policy",
        ordinal: 32,
    },
    FingerprintScenario {
        portfolio: "nightly-6",
        package: "release-crate-032",
        previous: (1, 5, 4),
        selected: (1, 5, 5),
        reason: "rustsec boundary",
        ordinal: 33,
    },
    FingerprintScenario {
        portfolio: "emergency-6",
        package: "release-crate-033",
        previous: (1, 6, 5),
        selected: (1, 6, 6),
        reason: "yanked index row",
        ordinal: 34,
    },
    FingerprintScenario {
        portfolio: "maintenance-6",
        package: "release-crate-034",
        previous: (1, 7, 6),
        selected: (1, 7, 7),
        reason: "toolchain floor",
        ordinal: 35,
    },
    FingerprintScenario {
        portfolio: "stable-7",
        package: "release-crate-035",
        previous: (1, 8, 0),
        selected: (1, 8, 1),
        reason: "source policy",
        ordinal: 36,
    },
    FingerprintScenario {
        portfolio: "candidate-7",
        package: "release-crate-036",
        previous: (1, 0, 1),
        selected: (1, 0, 2),
        reason: "rustsec boundary",
        ordinal: 37,
    },
    FingerprintScenario {
        portfolio: "nightly-7",
        package: "release-crate-037",
        previous: (1, 1, 2),
        selected: (1, 1, 3),
        reason: "yanked index row",
        ordinal: 38,
    },
    FingerprintScenario {
        portfolio: "emergency-7",
        package: "release-crate-038",
        previous: (1, 2, 3),
        selected: (1, 2, 4),
        reason: "toolchain floor",
        ordinal: 39,
    },
    FingerprintScenario {
        portfolio: "maintenance-7",
        package: "release-crate-039",
        previous: (1, 3, 4),
        selected: (1, 3, 5),
        reason: "source policy",
        ordinal: 40,
    },
    FingerprintScenario {
        portfolio: "stable-8",
        package: "release-crate-040",
        previous: (1, 4, 5),
        selected: (1, 4, 6),
        reason: "rustsec boundary",
        ordinal: 41,
    },
    FingerprintScenario {
        portfolio: "candidate-8",
        package: "release-crate-041",
        previous: (1, 5, 6),
        selected: (1, 5, 7),
        reason: "yanked index row",
        ordinal: 42,
    },
    FingerprintScenario {
        portfolio: "nightly-8",
        package: "release-crate-042",
        previous: (1, 6, 0),
        selected: (1, 6, 1),
        reason: "toolchain floor",
        ordinal: 43,
    },
    FingerprintScenario {
        portfolio: "emergency-8",
        package: "release-crate-043",
        previous: (1, 7, 1),
        selected: (1, 7, 2),
        reason: "source policy",
        ordinal: 44,
    },
    FingerprintScenario {
        portfolio: "maintenance-8",
        package: "release-crate-044",
        previous: (1, 8, 2),
        selected: (1, 8, 3),
        reason: "rustsec boundary",
        ordinal: 45,
    },
    FingerprintScenario {
        portfolio: "stable-9",
        package: "release-crate-045",
        previous: (1, 0, 3),
        selected: (1, 0, 4),
        reason: "yanked index row",
        ordinal: 46,
    },
    FingerprintScenario {
        portfolio: "candidate-9",
        package: "release-crate-046",
        previous: (1, 1, 4),
        selected: (1, 1, 5),
        reason: "toolchain floor",
        ordinal: 47,
    },
    FingerprintScenario {
        portfolio: "nightly-9",
        package: "release-crate-047",
        previous: (1, 2, 5),
        selected: (1, 2, 6),
        reason: "source policy",
        ordinal: 48,
    },
    FingerprintScenario {
        portfolio: "emergency-9",
        package: "release-crate-048",
        previous: (1, 3, 6),
        selected: (1, 3, 7),
        reason: "rustsec boundary",
        ordinal: 49,
    },
    FingerprintScenario {
        portfolio: "maintenance-9",
        package: "release-crate-049",
        previous: (1, 4, 0),
        selected: (1, 4, 1),
        reason: "yanked index row",
        ordinal: 50,
    },
    FingerprintScenario {
        portfolio: "stable-10",
        package: "release-crate-050",
        previous: (1, 5, 1),
        selected: (1, 5, 2),
        reason: "toolchain floor",
        ordinal: 51,
    },
    FingerprintScenario {
        portfolio: "candidate-10",
        package: "release-crate-051",
        previous: (1, 6, 2),
        selected: (1, 6, 3),
        reason: "source policy",
        ordinal: 52,
    },
    FingerprintScenario {
        portfolio: "nightly-10",
        package: "release-crate-052",
        previous: (1, 7, 3),
        selected: (1, 7, 4),
        reason: "rustsec boundary",
        ordinal: 53,
    },
    FingerprintScenario {
        portfolio: "emergency-10",
        package: "release-crate-053",
        previous: (1, 8, 4),
        selected: (1, 8, 5),
        reason: "yanked index row",
        ordinal: 54,
    },
    FingerprintScenario {
        portfolio: "maintenance-10",
        package: "release-crate-054",
        previous: (1, 0, 5),
        selected: (1, 0, 6),
        reason: "toolchain floor",
        ordinal: 55,
    },
    FingerprintScenario {
        portfolio: "stable-11",
        package: "release-crate-055",
        previous: (1, 1, 6),
        selected: (1, 1, 7),
        reason: "source policy",
        ordinal: 56,
    },
    FingerprintScenario {
        portfolio: "candidate-11",
        package: "release-crate-056",
        previous: (1, 2, 0),
        selected: (1, 2, 1),
        reason: "rustsec boundary",
        ordinal: 57,
    },
    FingerprintScenario {
        portfolio: "nightly-11",
        package: "release-crate-057",
        previous: (1, 3, 1),
        selected: (1, 3, 2),
        reason: "yanked index row",
        ordinal: 58,
    },
    FingerprintScenario {
        portfolio: "emergency-11",
        package: "release-crate-058",
        previous: (1, 4, 2),
        selected: (1, 4, 3),
        reason: "toolchain floor",
        ordinal: 59,
    },
    FingerprintScenario {
        portfolio: "maintenance-11",
        package: "release-crate-059",
        previous: (1, 5, 3),
        selected: (1, 5, 4),
        reason: "source policy",
        ordinal: 60,
    },
    FingerprintScenario {
        portfolio: "stable-12",
        package: "release-crate-060",
        previous: (1, 6, 4),
        selected: (1, 6, 5),
        reason: "rustsec boundary",
        ordinal: 61,
    },
    FingerprintScenario {
        portfolio: "candidate-12",
        package: "release-crate-061",
        previous: (1, 7, 5),
        selected: (1, 7, 6),
        reason: "yanked index row",
        ordinal: 62,
    },
    FingerprintScenario {
        portfolio: "nightly-12",
        package: "release-crate-062",
        previous: (1, 8, 6),
        selected: (1, 8, 7),
        reason: "toolchain floor",
        ordinal: 63,
    },
    FingerprintScenario {
        portfolio: "emergency-12",
        package: "release-crate-063",
        previous: (1, 0, 0),
        selected: (1, 0, 1),
        reason: "source policy",
        ordinal: 64,
    },
    FingerprintScenario {
        portfolio: "maintenance-12",
        package: "release-crate-064",
        previous: (1, 1, 1),
        selected: (1, 1, 2),
        reason: "rustsec boundary",
        ordinal: 65,
    },
    FingerprintScenario {
        portfolio: "stable-13",
        package: "release-crate-065",
        previous: (1, 2, 2),
        selected: (1, 2, 3),
        reason: "yanked index row",
        ordinal: 66,
    },
    FingerprintScenario {
        portfolio: "candidate-13",
        package: "release-crate-066",
        previous: (1, 3, 3),
        selected: (1, 3, 4),
        reason: "toolchain floor",
        ordinal: 67,
    },
    FingerprintScenario {
        portfolio: "nightly-13",
        package: "release-crate-067",
        previous: (1, 4, 4),
        selected: (1, 4, 5),
        reason: "source policy",
        ordinal: 68,
    },
    FingerprintScenario {
        portfolio: "emergency-13",
        package: "release-crate-068",
        previous: (1, 5, 5),
        selected: (1, 5, 6),
        reason: "rustsec boundary",
        ordinal: 69,
    },
    FingerprintScenario {
        portfolio: "maintenance-13",
        package: "release-crate-069",
        previous: (1, 6, 6),
        selected: (1, 6, 7),
        reason: "yanked index row",
        ordinal: 70,
    },
    FingerprintScenario {
        portfolio: "stable-14",
        package: "release-crate-070",
        previous: (1, 7, 0),
        selected: (1, 7, 1),
        reason: "toolchain floor",
        ordinal: 71,
    },
    FingerprintScenario {
        portfolio: "candidate-14",
        package: "release-crate-071",
        previous: (1, 8, 1),
        selected: (1, 8, 2),
        reason: "source policy",
        ordinal: 72,
    },
    FingerprintScenario {
        portfolio: "nightly-14",
        package: "release-crate-072",
        previous: (1, 0, 2),
        selected: (1, 0, 3),
        reason: "rustsec boundary",
        ordinal: 73,
    },
    FingerprintScenario {
        portfolio: "emergency-14",
        package: "release-crate-073",
        previous: (1, 1, 3),
        selected: (1, 1, 4),
        reason: "yanked index row",
        ordinal: 74,
    },
    FingerprintScenario {
        portfolio: "maintenance-14",
        package: "release-crate-074",
        previous: (1, 2, 4),
        selected: (1, 2, 5),
        reason: "toolchain floor",
        ordinal: 75,
    },
    FingerprintScenario {
        portfolio: "stable-15",
        package: "release-crate-075",
        previous: (1, 3, 5),
        selected: (1, 3, 6),
        reason: "source policy",
        ordinal: 76,
    },
    FingerprintScenario {
        portfolio: "candidate-15",
        package: "release-crate-076",
        previous: (1, 4, 6),
        selected: (1, 4, 7),
        reason: "rustsec boundary",
        ordinal: 77,
    },
    FingerprintScenario {
        portfolio: "nightly-15",
        package: "release-crate-077",
        previous: (1, 5, 0),
        selected: (1, 5, 1),
        reason: "yanked index row",
        ordinal: 78,
    },
    FingerprintScenario {
        portfolio: "emergency-15",
        package: "release-crate-078",
        previous: (1, 6, 1),
        selected: (1, 6, 2),
        reason: "toolchain floor",
        ordinal: 79,
    },
    FingerprintScenario {
        portfolio: "maintenance-15",
        package: "release-crate-079",
        previous: (1, 7, 2),
        selected: (1, 7, 3),
        reason: "source policy",
        ordinal: 80,
    },
];

#[test]
fn fingerprint_scenario_matrix_binds_every_release_change() {
    let mut fingerprints = BTreeSet::new();
    for scenario in FINGERPRINT_SCENARIOS {
        let change = DependencyChange {
            package: scenario.package.to_owned(),
            previous: Version::new(scenario.previous.0, scenario.previous.1, scenario.previous.2),
            selected: Version::new(scenario.selected.0, scenario.selected.1, scenario.selected.2),
            reason: format!("{} #{}", scenario.reason, scenario.ordinal),
        };
        let fingerprint = crate::release_fingerprint(scenario.portfolio, vec![change]);
        assert_eq!(fingerprint.len(), 64);
        assert!(fingerprints.insert(fingerprint), "{}", scenario.package);
    }
}
