use domain_model::DependencyChange;
use semver::Version;

#[derive(Debug, Clone, Copy)]
struct LedgerScenario {
    run_id: &'static str,
    package: &'static str,
    previous: (u64, u64, u64),
    selected: (u64, u64, u64),
    reason: &'static str,
}

const LEDGER_SCENARIOS: [LedgerScenario; 80] = [
    LedgerScenario {
        run_id: "fixture-run-000",
        package: "ledger-crate-000",
        previous: (1, 0, 0),
        selected: (1, 0, 1),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-001",
        package: "ledger-crate-001",
        previous: (1, 1, 1),
        selected: (1, 1, 2),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-002",
        package: "ledger-crate-002",
        previous: (1, 2, 2),
        selected: (1, 2, 3),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-003",
        package: "ledger-crate-003",
        previous: (1, 3, 3),
        selected: (1, 3, 4),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-004",
        package: "ledger-crate-004",
        previous: (1, 4, 4),
        selected: (1, 4, 5),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-005",
        package: "ledger-crate-005",
        previous: (1, 5, 5),
        selected: (1, 5, 6),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-006",
        package: "ledger-crate-006",
        previous: (1, 6, 6),
        selected: (1, 6, 7),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-007",
        package: "ledger-crate-007",
        previous: (1, 7, 7),
        selected: (1, 7, 8),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-008",
        package: "ledger-crate-008",
        previous: (1, 8, 0),
        selected: (1, 8, 1),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-009",
        package: "ledger-crate-009",
        previous: (1, 9, 1),
        selected: (1, 9, 2),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-010",
        package: "ledger-crate-010",
        previous: (1, 0, 2),
        selected: (1, 0, 3),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-011",
        package: "ledger-crate-011",
        previous: (1, 1, 3),
        selected: (1, 1, 4),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-012",
        package: "ledger-crate-012",
        previous: (1, 2, 4),
        selected: (1, 2, 5),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-013",
        package: "ledger-crate-013",
        previous: (1, 3, 5),
        selected: (1, 3, 6),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-014",
        package: "ledger-crate-014",
        previous: (1, 4, 6),
        selected: (1, 4, 7),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-015",
        package: "ledger-crate-015",
        previous: (1, 5, 7),
        selected: (1, 5, 8),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-016",
        package: "ledger-crate-016",
        previous: (1, 6, 0),
        selected: (1, 6, 1),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-017",
        package: "ledger-crate-017",
        previous: (1, 7, 1),
        selected: (1, 7, 2),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-018",
        package: "ledger-crate-018",
        previous: (1, 8, 2),
        selected: (1, 8, 3),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-019",
        package: "ledger-crate-019",
        previous: (1, 9, 3),
        selected: (1, 9, 4),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-020",
        package: "ledger-crate-020",
        previous: (1, 0, 4),
        selected: (1, 0, 5),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-021",
        package: "ledger-crate-021",
        previous: (1, 1, 5),
        selected: (1, 1, 6),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-022",
        package: "ledger-crate-022",
        previous: (1, 2, 6),
        selected: (1, 2, 7),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-023",
        package: "ledger-crate-023",
        previous: (1, 3, 7),
        selected: (1, 3, 8),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-024",
        package: "ledger-crate-024",
        previous: (1, 4, 0),
        selected: (1, 4, 1),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-025",
        package: "ledger-crate-025",
        previous: (1, 5, 1),
        selected: (1, 5, 2),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-026",
        package: "ledger-crate-026",
        previous: (1, 6, 2),
        selected: (1, 6, 3),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-027",
        package: "ledger-crate-027",
        previous: (1, 7, 3),
        selected: (1, 7, 4),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-028",
        package: "ledger-crate-028",
        previous: (1, 8, 4),
        selected: (1, 8, 5),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-029",
        package: "ledger-crate-029",
        previous: (1, 9, 5),
        selected: (1, 9, 6),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-030",
        package: "ledger-crate-030",
        previous: (1, 0, 6),
        selected: (1, 0, 7),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-031",
        package: "ledger-crate-031",
        previous: (1, 1, 7),
        selected: (1, 1, 8),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-032",
        package: "ledger-crate-032",
        previous: (1, 2, 0),
        selected: (1, 2, 1),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-033",
        package: "ledger-crate-033",
        previous: (1, 3, 1),
        selected: (1, 3, 2),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-034",
        package: "ledger-crate-034",
        previous: (1, 4, 2),
        selected: (1, 4, 3),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-035",
        package: "ledger-crate-035",
        previous: (1, 5, 3),
        selected: (1, 5, 4),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-036",
        package: "ledger-crate-036",
        previous: (1, 6, 4),
        selected: (1, 6, 5),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-037",
        package: "ledger-crate-037",
        previous: (1, 7, 5),
        selected: (1, 7, 6),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-038",
        package: "ledger-crate-038",
        previous: (1, 8, 6),
        selected: (1, 8, 7),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-039",
        package: "ledger-crate-039",
        previous: (1, 9, 7),
        selected: (1, 9, 8),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-040",
        package: "ledger-crate-040",
        previous: (1, 0, 0),
        selected: (1, 0, 1),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-041",
        package: "ledger-crate-041",
        previous: (1, 1, 1),
        selected: (1, 1, 2),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-042",
        package: "ledger-crate-042",
        previous: (1, 2, 2),
        selected: (1, 2, 3),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-043",
        package: "ledger-crate-043",
        previous: (1, 3, 3),
        selected: (1, 3, 4),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-044",
        package: "ledger-crate-044",
        previous: (1, 4, 4),
        selected: (1, 4, 5),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-045",
        package: "ledger-crate-045",
        previous: (1, 5, 5),
        selected: (1, 5, 6),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-046",
        package: "ledger-crate-046",
        previous: (1, 6, 6),
        selected: (1, 6, 7),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-047",
        package: "ledger-crate-047",
        previous: (1, 7, 7),
        selected: (1, 7, 8),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-048",
        package: "ledger-crate-048",
        previous: (1, 8, 0),
        selected: (1, 8, 1),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-049",
        package: "ledger-crate-049",
        previous: (1, 9, 1),
        selected: (1, 9, 2),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-050",
        package: "ledger-crate-050",
        previous: (1, 0, 2),
        selected: (1, 0, 3),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-051",
        package: "ledger-crate-051",
        previous: (1, 1, 3),
        selected: (1, 1, 4),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-052",
        package: "ledger-crate-052",
        previous: (1, 2, 4),
        selected: (1, 2, 5),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-053",
        package: "ledger-crate-053",
        previous: (1, 3, 5),
        selected: (1, 3, 6),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-054",
        package: "ledger-crate-054",
        previous: (1, 4, 6),
        selected: (1, 4, 7),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-055",
        package: "ledger-crate-055",
        previous: (1, 5, 7),
        selected: (1, 5, 8),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-056",
        package: "ledger-crate-056",
        previous: (1, 6, 0),
        selected: (1, 6, 1),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-057",
        package: "ledger-crate-057",
        previous: (1, 7, 1),
        selected: (1, 7, 2),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-058",
        package: "ledger-crate-058",
        previous: (1, 8, 2),
        selected: (1, 8, 3),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-059",
        package: "ledger-crate-059",
        previous: (1, 9, 3),
        selected: (1, 9, 4),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-060",
        package: "ledger-crate-060",
        previous: (1, 0, 4),
        selected: (1, 0, 5),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-061",
        package: "ledger-crate-061",
        previous: (1, 1, 5),
        selected: (1, 1, 6),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-062",
        package: "ledger-crate-062",
        previous: (1, 2, 6),
        selected: (1, 2, 7),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-063",
        package: "ledger-crate-063",
        previous: (1, 3, 7),
        selected: (1, 3, 8),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-064",
        package: "ledger-crate-064",
        previous: (1, 4, 0),
        selected: (1, 4, 1),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-065",
        package: "ledger-crate-065",
        previous: (1, 5, 1),
        selected: (1, 5, 2),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-066",
        package: "ledger-crate-066",
        previous: (1, 6, 2),
        selected: (1, 6, 3),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-067",
        package: "ledger-crate-067",
        previous: (1, 7, 3),
        selected: (1, 7, 4),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-068",
        package: "ledger-crate-068",
        previous: (1, 8, 4),
        selected: (1, 8, 5),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-069",
        package: "ledger-crate-069",
        previous: (1, 9, 5),
        selected: (1, 9, 6),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-070",
        package: "ledger-crate-070",
        previous: (1, 0, 6),
        selected: (1, 0, 7),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-071",
        package: "ledger-crate-071",
        previous: (1, 1, 7),
        selected: (1, 1, 8),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-072",
        package: "ledger-crate-072",
        previous: (1, 2, 0),
        selected: (1, 2, 1),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-073",
        package: "ledger-crate-073",
        previous: (1, 3, 1),
        selected: (1, 3, 2),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-074",
        package: "ledger-crate-074",
        previous: (1, 4, 2),
        selected: (1, 4, 3),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-075",
        package: "ledger-crate-075",
        previous: (1, 5, 3),
        selected: (1, 5, 4),
        reason: "registry",
    },
    LedgerScenario {
        run_id: "fixture-run-076",
        package: "ledger-crate-076",
        previous: (1, 6, 4),
        selected: (1, 6, 5),
        reason: "advisory",
    },
    LedgerScenario {
        run_id: "fixture-run-077",
        package: "ledger-crate-077",
        previous: (1, 7, 5),
        selected: (1, 7, 6),
        reason: "yank",
    },
    LedgerScenario {
        run_id: "fixture-run-078",
        package: "ledger-crate-078",
        previous: (1, 8, 6),
        selected: (1, 8, 7),
        reason: "msrv",
    },
    LedgerScenario {
        run_id: "fixture-run-079",
        package: "ledger-crate-079",
        previous: (1, 9, 7),
        selected: (1, 9, 8),
        reason: "registry",
    },
];

#[test]
fn ledger_scenario_matrix_persists_normalized_changes() {
    let connection = crate::open_memory().unwrap();
    for scenario in LEDGER_SCENARIOS {
        connection
            .execute("INSERT INTO runtime_runs(run_id) VALUES(?1)", [scenario.run_id])
            .unwrap();
        let change = DependencyChange {
            package: scenario.package.to_owned(),
            previous: Version::new(scenario.previous.0, scenario.previous.1, scenario.previous.2),
            selected: Version::new(scenario.selected.0, scenario.selected.1, scenario.selected.2),
            reason: scenario.reason.to_owned(),
        };
        crate::record_change(&connection, scenario.run_id, &change).unwrap();
    }
    let count: i64 = connection
        .query_row("SELECT count(*) FROM runtime_changes", [], |row| row.get(0))
        .unwrap();
    assert_eq!(count, LEDGER_SCENARIOS.len() as i64);
}
