// Code generated by scripts/gen_heat.py from config/baselines/heat.env. DO NOT EDIT.
package season

const HeatDefaultEra = "heat-v2"

const (
	RowSlack         = 1
	TargetPad        = 1
	FlipLatchSeed    = 0
	LeaveLatchSeed   = 0
	PrinterWinFloor  = 2
	MajorityScore    = 70
)

const AggregateScale = 1.15

const ChampionshipMode = 0
