use std::collections::BTreeSet;

#[derive(Debug, Clone, Copy)]
struct DigestScenario {
    label: &'static str,
    namespace: &'static str,
    object_kind: &'static str,
    sequence: u32,
    payload: &'static str,
    salt: &'static str,
}

const DIGEST_SCENARIOS: [DigestScenario; 80] = [
    DigestScenario {
        label: "digest-case-000",
        namespace: "lock",
        object_kind: "manifest",
        sequence: 1000,
        payload: "fixture-payload-000",
        salt: "ring-00",
    },
    DigestScenario {
        label: "digest-case-001",
        namespace: "vendor",
        object_kind: "package",
        sequence: 1001,
        payload: "fixture-payload-001",
        salt: "ring-01",
    },
    DigestScenario {
        label: "digest-case-002",
        namespace: "ledger",
        object_kind: "run",
        sequence: 1002,
        payload: "fixture-payload-002",
        salt: "ring-02",
    },
    DigestScenario {
        label: "digest-case-003",
        namespace: "advisory",
        object_kind: "check",
        sequence: 1003,
        payload: "fixture-payload-003",
        salt: "ring-03",
    },
    DigestScenario {
        label: "digest-case-004",
        namespace: "registry",
        object_kind: "manifest",
        sequence: 1004,
        payload: "fixture-payload-004",
        salt: "ring-04",
    },
    DigestScenario {
        label: "digest-case-005",
        namespace: "lock",
        object_kind: "package",
        sequence: 1005,
        payload: "fixture-payload-005",
        salt: "ring-05",
    },
    DigestScenario {
        label: "digest-case-006",
        namespace: "vendor",
        object_kind: "run",
        sequence: 1006,
        payload: "fixture-payload-006",
        salt: "ring-06",
    },
    DigestScenario {
        label: "digest-case-007",
        namespace: "ledger",
        object_kind: "check",
        sequence: 1007,
        payload: "fixture-payload-007",
        salt: "ring-07",
    },
    DigestScenario {
        label: "digest-case-008",
        namespace: "advisory",
        object_kind: "manifest",
        sequence: 1008,
        payload: "fixture-payload-008",
        salt: "ring-08",
    },
    DigestScenario {
        label: "digest-case-009",
        namespace: "registry",
        object_kind: "package",
        sequence: 1009,
        payload: "fixture-payload-009",
        salt: "ring-00",
    },
    DigestScenario {
        label: "digest-case-010",
        namespace: "lock",
        object_kind: "run",
        sequence: 1010,
        payload: "fixture-payload-010",
        salt: "ring-01",
    },
    DigestScenario {
        label: "digest-case-011",
        namespace: "vendor",
        object_kind: "check",
        sequence: 1011,
        payload: "fixture-payload-011",
        salt: "ring-02",
    },
    DigestScenario {
        label: "digest-case-012",
        namespace: "ledger",
        object_kind: "manifest",
        sequence: 1012,
        payload: "fixture-payload-012",
        salt: "ring-03",
    },
    DigestScenario {
        label: "digest-case-013",
        namespace: "advisory",
        object_kind: "package",
        sequence: 1013,
        payload: "fixture-payload-013",
        salt: "ring-04",
    },
    DigestScenario {
        label: "digest-case-014",
        namespace: "registry",
        object_kind: "run",
        sequence: 1014,
        payload: "fixture-payload-014",
        salt: "ring-05",
    },
    DigestScenario {
        label: "digest-case-015",
        namespace: "lock",
        object_kind: "check",
        sequence: 1015,
        payload: "fixture-payload-015",
        salt: "ring-06",
    },
    DigestScenario {
        label: "digest-case-016",
        namespace: "vendor",
        object_kind: "manifest",
        sequence: 1016,
        payload: "fixture-payload-016",
        salt: "ring-07",
    },
    DigestScenario {
        label: "digest-case-017",
        namespace: "ledger",
        object_kind: "package",
        sequence: 1017,
        payload: "fixture-payload-017",
        salt: "ring-08",
    },
    DigestScenario {
        label: "digest-case-018",
        namespace: "advisory",
        object_kind: "run",
        sequence: 1018,
        payload: "fixture-payload-018",
        salt: "ring-00",
    },
    DigestScenario {
        label: "digest-case-019",
        namespace: "registry",
        object_kind: "check",
        sequence: 1019,
        payload: "fixture-payload-019",
        salt: "ring-01",
    },
    DigestScenario {
        label: "digest-case-020",
        namespace: "lock",
        object_kind: "manifest",
        sequence: 1020,
        payload: "fixture-payload-020",
        salt: "ring-02",
    },
    DigestScenario {
        label: "digest-case-021",
        namespace: "vendor",
        object_kind: "package",
        sequence: 1021,
        payload: "fixture-payload-021",
        salt: "ring-03",
    },
    DigestScenario {
        label: "digest-case-022",
        namespace: "ledger",
        object_kind: "run",
        sequence: 1022,
        payload: "fixture-payload-022",
        salt: "ring-04",
    },
    DigestScenario {
        label: "digest-case-023",
        namespace: "advisory",
        object_kind: "check",
        sequence: 1023,
        payload: "fixture-payload-023",
        salt: "ring-05",
    },
    DigestScenario {
        label: "digest-case-024",
        namespace: "registry",
        object_kind: "manifest",
        sequence: 1024,
        payload: "fixture-payload-024",
        salt: "ring-06",
    },
    DigestScenario {
        label: "digest-case-025",
        namespace: "lock",
        object_kind: "package",
        sequence: 1025,
        payload: "fixture-payload-025",
        salt: "ring-07",
    },
    DigestScenario {
        label: "digest-case-026",
        namespace: "vendor",
        object_kind: "run",
        sequence: 1026,
        payload: "fixture-payload-026",
        salt: "ring-08",
    },
    DigestScenario {
        label: "digest-case-027",
        namespace: "ledger",
        object_kind: "check",
        sequence: 1027,
        payload: "fixture-payload-027",
        salt: "ring-00",
    },
    DigestScenario {
        label: "digest-case-028",
        namespace: "advisory",
        object_kind: "manifest",
        sequence: 1028,
        payload: "fixture-payload-028",
        salt: "ring-01",
    },
    DigestScenario {
        label: "digest-case-029",
        namespace: "registry",
        object_kind: "package",
        sequence: 1029,
        payload: "fixture-payload-029",
        salt: "ring-02",
    },
    DigestScenario {
        label: "digest-case-030",
        namespace: "lock",
        object_kind: "run",
        sequence: 1030,
        payload: "fixture-payload-030",
        salt: "ring-03",
    },
    DigestScenario {
        label: "digest-case-031",
        namespace: "vendor",
        object_kind: "check",
        sequence: 1031,
        payload: "fixture-payload-031",
        salt: "ring-04",
    },
    DigestScenario {
        label: "digest-case-032",
        namespace: "ledger",
        object_kind: "manifest",
        sequence: 1032,
        payload: "fixture-payload-032",
        salt: "ring-05",
    },
    DigestScenario {
        label: "digest-case-033",
        namespace: "advisory",
        object_kind: "package",
        sequence: 1033,
        payload: "fixture-payload-033",
        salt: "ring-06",
    },
    DigestScenario {
        label: "digest-case-034",
        namespace: "registry",
        object_kind: "run",
        sequence: 1034,
        payload: "fixture-payload-034",
        salt: "ring-07",
    },
    DigestScenario {
        label: "digest-case-035",
        namespace: "lock",
        object_kind: "check",
        sequence: 1035,
        payload: "fixture-payload-035",
        salt: "ring-08",
    },
    DigestScenario {
        label: "digest-case-036",
        namespace: "vendor",
        object_kind: "manifest",
        sequence: 1036,
        payload: "fixture-payload-036",
        salt: "ring-00",
    },
    DigestScenario {
        label: "digest-case-037",
        namespace: "ledger",
        object_kind: "package",
        sequence: 1037,
        payload: "fixture-payload-037",
        salt: "ring-01",
    },
    DigestScenario {
        label: "digest-case-038",
        namespace: "advisory",
        object_kind: "run",
        sequence: 1038,
        payload: "fixture-payload-038",
        salt: "ring-02",
    },
    DigestScenario {
        label: "digest-case-039",
        namespace: "registry",
        object_kind: "check",
        sequence: 1039,
        payload: "fixture-payload-039",
        salt: "ring-03",
    },
    DigestScenario {
        label: "digest-case-040",
        namespace: "lock",
        object_kind: "manifest",
        sequence: 1040,
        payload: "fixture-payload-040",
        salt: "ring-04",
    },
    DigestScenario {
        label: "digest-case-041",
        namespace: "vendor",
        object_kind: "package",
        sequence: 1041,
        payload: "fixture-payload-041",
        salt: "ring-05",
    },
    DigestScenario {
        label: "digest-case-042",
        namespace: "ledger",
        object_kind: "run",
        sequence: 1042,
        payload: "fixture-payload-042",
        salt: "ring-06",
    },
    DigestScenario {
        label: "digest-case-043",
        namespace: "advisory",
        object_kind: "check",
        sequence: 1043,
        payload: "fixture-payload-043",
        salt: "ring-07",
    },
    DigestScenario {
        label: "digest-case-044",
        namespace: "registry",
        object_kind: "manifest",
        sequence: 1044,
        payload: "fixture-payload-044",
        salt: "ring-08",
    },
    DigestScenario {
        label: "digest-case-045",
        namespace: "lock",
        object_kind: "package",
        sequence: 1045,
        payload: "fixture-payload-045",
        salt: "ring-00",
    },
    DigestScenario {
        label: "digest-case-046",
        namespace: "vendor",
        object_kind: "run",
        sequence: 1046,
        payload: "fixture-payload-046",
        salt: "ring-01",
    },
    DigestScenario {
        label: "digest-case-047",
        namespace: "ledger",
        object_kind: "check",
        sequence: 1047,
        payload: "fixture-payload-047",
        salt: "ring-02",
    },
    DigestScenario {
        label: "digest-case-048",
        namespace: "advisory",
        object_kind: "manifest",
        sequence: 1048,
        payload: "fixture-payload-048",
        salt: "ring-03",
    },
    DigestScenario {
        label: "digest-case-049",
        namespace: "registry",
        object_kind: "package",
        sequence: 1049,
        payload: "fixture-payload-049",
        salt: "ring-04",
    },
    DigestScenario {
        label: "digest-case-050",
        namespace: "lock",
        object_kind: "run",
        sequence: 1050,
        payload: "fixture-payload-050",
        salt: "ring-05",
    },
    DigestScenario {
        label: "digest-case-051",
        namespace: "vendor",
        object_kind: "check",
        sequence: 1051,
        payload: "fixture-payload-051",
        salt: "ring-06",
    },
    DigestScenario {
        label: "digest-case-052",
        namespace: "ledger",
        object_kind: "manifest",
        sequence: 1052,
        payload: "fixture-payload-052",
        salt: "ring-07",
    },
    DigestScenario {
        label: "digest-case-053",
        namespace: "advisory",
        object_kind: "package",
        sequence: 1053,
        payload: "fixture-payload-053",
        salt: "ring-08",
    },
    DigestScenario {
        label: "digest-case-054",
        namespace: "registry",
        object_kind: "run",
        sequence: 1054,
        payload: "fixture-payload-054",
        salt: "ring-00",
    },
    DigestScenario {
        label: "digest-case-055",
        namespace: "lock",
        object_kind: "check",
        sequence: 1055,
        payload: "fixture-payload-055",
        salt: "ring-01",
    },
    DigestScenario {
        label: "digest-case-056",
        namespace: "vendor",
        object_kind: "manifest",
        sequence: 1056,
        payload: "fixture-payload-056",
        salt: "ring-02",
    },
    DigestScenario {
        label: "digest-case-057",
        namespace: "ledger",
        object_kind: "package",
        sequence: 1057,
        payload: "fixture-payload-057",
        salt: "ring-03",
    },
    DigestScenario {
        label: "digest-case-058",
        namespace: "advisory",
        object_kind: "run",
        sequence: 1058,
        payload: "fixture-payload-058",
        salt: "ring-04",
    },
    DigestScenario {
        label: "digest-case-059",
        namespace: "registry",
        object_kind: "check",
        sequence: 1059,
        payload: "fixture-payload-059",
        salt: "ring-05",
    },
    DigestScenario {
        label: "digest-case-060",
        namespace: "lock",
        object_kind: "manifest",
        sequence: 1060,
        payload: "fixture-payload-060",
        salt: "ring-06",
    },
    DigestScenario {
        label: "digest-case-061",
        namespace: "vendor",
        object_kind: "package",
        sequence: 1061,
        payload: "fixture-payload-061",
        salt: "ring-07",
    },
    DigestScenario {
        label: "digest-case-062",
        namespace: "ledger",
        object_kind: "run",
        sequence: 1062,
        payload: "fixture-payload-062",
        salt: "ring-08",
    },
    DigestScenario {
        label: "digest-case-063",
        namespace: "advisory",
        object_kind: "check",
        sequence: 1063,
        payload: "fixture-payload-063",
        salt: "ring-00",
    },
    DigestScenario {
        label: "digest-case-064",
        namespace: "registry",
        object_kind: "manifest",
        sequence: 1064,
        payload: "fixture-payload-064",
        salt: "ring-01",
    },
    DigestScenario {
        label: "digest-case-065",
        namespace: "lock",
        object_kind: "package",
        sequence: 1065,
        payload: "fixture-payload-065",
        salt: "ring-02",
    },
    DigestScenario {
        label: "digest-case-066",
        namespace: "vendor",
        object_kind: "run",
        sequence: 1066,
        payload: "fixture-payload-066",
        salt: "ring-03",
    },
    DigestScenario {
        label: "digest-case-067",
        namespace: "ledger",
        object_kind: "check",
        sequence: 1067,
        payload: "fixture-payload-067",
        salt: "ring-04",
    },
    DigestScenario {
        label: "digest-case-068",
        namespace: "advisory",
        object_kind: "manifest",
        sequence: 1068,
        payload: "fixture-payload-068",
        salt: "ring-05",
    },
    DigestScenario {
        label: "digest-case-069",
        namespace: "registry",
        object_kind: "package",
        sequence: 1069,
        payload: "fixture-payload-069",
        salt: "ring-06",
    },
    DigestScenario {
        label: "digest-case-070",
        namespace: "lock",
        object_kind: "run",
        sequence: 1070,
        payload: "fixture-payload-070",
        salt: "ring-07",
    },
    DigestScenario {
        label: "digest-case-071",
        namespace: "vendor",
        object_kind: "check",
        sequence: 1071,
        payload: "fixture-payload-071",
        salt: "ring-08",
    },
    DigestScenario {
        label: "digest-case-072",
        namespace: "ledger",
        object_kind: "manifest",
        sequence: 1072,
        payload: "fixture-payload-072",
        salt: "ring-00",
    },
    DigestScenario {
        label: "digest-case-073",
        namespace: "advisory",
        object_kind: "package",
        sequence: 1073,
        payload: "fixture-payload-073",
        salt: "ring-01",
    },
    DigestScenario {
        label: "digest-case-074",
        namespace: "registry",
        object_kind: "run",
        sequence: 1074,
        payload: "fixture-payload-074",
        salt: "ring-02",
    },
    DigestScenario {
        label: "digest-case-075",
        namespace: "lock",
        object_kind: "check",
        sequence: 1075,
        payload: "fixture-payload-075",
        salt: "ring-03",
    },
    DigestScenario {
        label: "digest-case-076",
        namespace: "vendor",
        object_kind: "manifest",
        sequence: 1076,
        payload: "fixture-payload-076",
        salt: "ring-04",
    },
    DigestScenario {
        label: "digest-case-077",
        namespace: "ledger",
        object_kind: "package",
        sequence: 1077,
        payload: "fixture-payload-077",
        salt: "ring-05",
    },
    DigestScenario {
        label: "digest-case-078",
        namespace: "advisory",
        object_kind: "run",
        sequence: 1078,
        payload: "fixture-payload-078",
        salt: "ring-06",
    },
    DigestScenario {
        label: "digest-case-079",
        namespace: "registry",
        object_kind: "check",
        sequence: 1079,
        payload: "fixture-payload-079",
        salt: "ring-07",
    },
];

#[test]
fn digest_scenario_matrix_is_deterministic_and_collision_free() {
    let mut seen = BTreeSet::new();
    for scenario in DIGEST_SCENARIOS {
        let bytes = format!(
            "{}\0{}\0{}\0{}\0{}",
            scenario.namespace,
            scenario.object_kind,
            scenario.sequence,
            scenario.payload,
            scenario.salt,
        );
        let first = crate::digest(bytes.as_bytes());
        let second = crate::digest(bytes.as_bytes());
        assert_eq!(first, second, "{}", scenario.label);
        assert_eq!(first.len(), 64);
        assert!(seen.insert(first), "{}", scenario.label);
    }
}
