/* @generated by mkscore from config/severity.map; do not edit. */
#ifndef RISK_SEVERITY_TABLE_H
#define RISK_SEVERITY_TABLE_H

#define SEV_LABEL_CRITICAL 100
#define SEV_LABEL_HIGH 80
#define SEV_LABEL_MODERATE 50
#define SEV_LABEL_LOW 20
#define COEFF_EXTRA_GROUP 5
#define COEFF_PAGE 1
#define RISK_CAP 100

#endif
