use std::time::Duration;

use domain_model::DependencyChange;
use semver::Version;

#[derive(Debug, Clone, Copy)]
struct QueueScenario {
    name: &'static str,
    capacity: usize,
    offers: usize,
    drains: usize,
    wait_millis: u64,
    expected_pending: usize,
}

const QUEUE_SCENARIOS: [QueueScenario; 80] = [
    QueueScenario {
        name: "queue-case-000",
        capacity: 2,
        offers: 1,
        drains: 0,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-001",
        capacity: 3,
        offers: 2,
        drains: 1,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-002",
        capacity: 4,
        offers: 3,
        drains: 2,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-003",
        capacity: 5,
        offers: 4,
        drains: 3,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-004",
        capacity: 6,
        offers: 5,
        drains: 4,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-005",
        capacity: 7,
        offers: 6,
        drains: 5,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-006",
        capacity: 8,
        offers: 7,
        drains: 6,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-007",
        capacity: 9,
        offers: 8,
        drains: 7,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-008",
        capacity: 10,
        offers: 9,
        drains: 8,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-009",
        capacity: 2,
        offers: 2,
        drains: 0,
        wait_millis: 5,
        expected_pending: 2,
    },
    QueueScenario {
        name: "queue-case-010",
        capacity: 3,
        offers: 2,
        drains: 1,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-011",
        capacity: 4,
        offers: 4,
        drains: 1,
        wait_millis: 5,
        expected_pending: 3,
    },
    QueueScenario {
        name: "queue-case-012",
        capacity: 5,
        offers: 3,
        drains: 0,
        wait_millis: 5,
        expected_pending: 3,
    },
    QueueScenario {
        name: "queue-case-013",
        capacity: 6,
        offers: 2,
        drains: 1,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-014",
        capacity: 7,
        offers: 1,
        drains: 0,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-015",
        capacity: 8,
        offers: 8,
        drains: 6,
        wait_millis: 5,
        expected_pending: 2,
    },
    QueueScenario {
        name: "queue-case-016",
        capacity: 9,
        offers: 8,
        drains: 7,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-017",
        capacity: 10,
        offers: 8,
        drains: 8,
        wait_millis: 5,
        expected_pending: 0,
    },
    QueueScenario {
        name: "queue-case-018",
        capacity: 2,
        offers: 1,
        drains: 0,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-019",
        capacity: 3,
        offers: 2,
        drains: 1,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-020",
        capacity: 4,
        offers: 1,
        drains: 0,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-021",
        capacity: 5,
        offers: 2,
        drains: 0,
        wait_millis: 5,
        expected_pending: 2,
    },
    QueueScenario {
        name: "queue-case-022",
        capacity: 6,
        offers: 5,
        drains: 4,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-023",
        capacity: 7,
        offers: 3,
        drains: 3,
        wait_millis: 5,
        expected_pending: 0,
    },
    QueueScenario {
        name: "queue-case-024",
        capacity: 8,
        offers: 1,
        drains: 0,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-025",
        capacity: 9,
        offers: 8,
        drains: 7,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-026",
        capacity: 10,
        offers: 7,
        drains: 2,
        wait_millis: 5,
        expected_pending: 5,
    },
    QueueScenario {
        name: "queue-case-027",
        capacity: 2,
        offers: 2,
        drains: 0,
        wait_millis: 5,
        expected_pending: 2,
    },
    QueueScenario {
        name: "queue-case-028",
        capacity: 3,
        offers: 2,
        drains: 1,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-029",
        capacity: 4,
        offers: 2,
        drains: 2,
        wait_millis: 5,
        expected_pending: 0,
    },
    QueueScenario {
        name: "queue-case-030",
        capacity: 5,
        offers: 1,
        drains: 0,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-031",
        capacity: 6,
        offers: 2,
        drains: 1,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-032",
        capacity: 7,
        offers: 5,
        drains: 2,
        wait_millis: 5,
        expected_pending: 3,
    },
    QueueScenario {
        name: "queue-case-033",
        capacity: 8,
        offers: 2,
        drains: 0,
        wait_millis: 5,
        expected_pending: 2,
    },
    QueueScenario {
        name: "queue-case-034",
        capacity: 9,
        offers: 8,
        drains: 7,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-035",
        capacity: 10,
        offers: 6,
        drains: 0,
        wait_millis: 5,
        expected_pending: 6,
    },
    QueueScenario {
        name: "queue-case-036",
        capacity: 2,
        offers: 1,
        drains: 0,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-037",
        capacity: 3,
        offers: 2,
        drains: 1,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-038",
        capacity: 4,
        offers: 3,
        drains: 2,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-039",
        capacity: 5,
        offers: 5,
        drains: 3,
        wait_millis: 5,
        expected_pending: 2,
    },
    QueueScenario {
        name: "queue-case-040",
        capacity: 6,
        offers: 5,
        drains: 4,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-041",
        capacity: 7,
        offers: 7,
        drains: 1,
        wait_millis: 5,
        expected_pending: 6,
    },
    QueueScenario {
        name: "queue-case-042",
        capacity: 8,
        offers: 3,
        drains: 2,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-043",
        capacity: 9,
        offers: 8,
        drains: 7,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-044",
        capacity: 10,
        offers: 5,
        drains: 2,
        wait_millis: 5,
        expected_pending: 3,
    },
    QueueScenario {
        name: "queue-case-045",
        capacity: 2,
        offers: 2,
        drains: 0,
        wait_millis: 5,
        expected_pending: 2,
    },
    QueueScenario {
        name: "queue-case-046",
        capacity: 3,
        offers: 2,
        drains: 1,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-047",
        capacity: 4,
        offers: 4,
        drains: 2,
        wait_millis: 5,
        expected_pending: 2,
    },
    QueueScenario {
        name: "queue-case-048",
        capacity: 5,
        offers: 4,
        drains: 3,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-049",
        capacity: 6,
        offers: 2,
        drains: 1,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-050",
        capacity: 7,
        offers: 2,
        drains: 2,
        wait_millis: 5,
        expected_pending: 0,
    },
    QueueScenario {
        name: "queue-case-051",
        capacity: 8,
        offers: 4,
        drains: 1,
        wait_millis: 5,
        expected_pending: 3,
    },
    QueueScenario {
        name: "queue-case-052",
        capacity: 9,
        offers: 8,
        drains: 7,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-053",
        capacity: 10,
        offers: 4,
        drains: 3,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-054",
        capacity: 2,
        offers: 1,
        drains: 0,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-055",
        capacity: 3,
        offers: 2,
        drains: 1,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-056",
        capacity: 4,
        offers: 1,
        drains: 0,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-057",
        capacity: 5,
        offers: 3,
        drains: 1,
        wait_millis: 5,
        expected_pending: 2,
    },
    QueueScenario {
        name: "queue-case-058",
        capacity: 6,
        offers: 5,
        drains: 4,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-059",
        capacity: 7,
        offers: 4,
        drains: 4,
        wait_millis: 5,
        expected_pending: 0,
    },
    QueueScenario {
        name: "queue-case-060",
        capacity: 8,
        offers: 5,
        drains: 0,
        wait_millis: 5,
        expected_pending: 5,
    },
    QueueScenario {
        name: "queue-case-061",
        capacity: 9,
        offers: 8,
        drains: 7,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-062",
        capacity: 10,
        offers: 3,
        drains: 2,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-063",
        capacity: 2,
        offers: 2,
        drains: 0,
        wait_millis: 5,
        expected_pending: 2,
    },
    QueueScenario {
        name: "queue-case-064",
        capacity: 3,
        offers: 2,
        drains: 1,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-065",
        capacity: 4,
        offers: 2,
        drains: 2,
        wait_millis: 5,
        expected_pending: 0,
    },
    QueueScenario {
        name: "queue-case-066",
        capacity: 5,
        offers: 2,
        drains: 0,
        wait_millis: 5,
        expected_pending: 2,
    },
    QueueScenario {
        name: "queue-case-067",
        capacity: 6,
        offers: 2,
        drains: 1,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-068",
        capacity: 7,
        offers: 6,
        drains: 5,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-069",
        capacity: 8,
        offers: 6,
        drains: 6,
        wait_millis: 5,
        expected_pending: 0,
    },
    QueueScenario {
        name: "queue-case-070",
        capacity: 9,
        offers: 8,
        drains: 7,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-071",
        capacity: 10,
        offers: 2,
        drains: 2,
        wait_millis: 5,
        expected_pending: 0,
    },
    QueueScenario {
        name: "queue-case-072",
        capacity: 2,
        offers: 1,
        drains: 0,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-073",
        capacity: 3,
        offers: 2,
        drains: 1,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-074",
        capacity: 4,
        offers: 3,
        drains: 2,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-075",
        capacity: 5,
        offers: 1,
        drains: 1,
        wait_millis: 5,
        expected_pending: 0,
    },
    QueueScenario {
        name: "queue-case-076",
        capacity: 6,
        offers: 5,
        drains: 4,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-077",
        capacity: 7,
        offers: 1,
        drains: 1,
        wait_millis: 5,
        expected_pending: 0,
    },
    QueueScenario {
        name: "queue-case-078",
        capacity: 8,
        offers: 7,
        drains: 6,
        wait_millis: 5,
        expected_pending: 1,
    },
    QueueScenario {
        name: "queue-case-079",
        capacity: 9,
        offers: 8,
        drains: 7,
        wait_millis: 5,
        expected_pending: 1,
    },
];

#[test]
fn queue_scenario_matrix_preserves_capacity_and_drain_counts() {
    for scenario in QUEUE_SCENARIOS {
        let queue = crate::ReleaseQueue::with_capacity(scenario.capacity);
        for index in 0..scenario.offers {
            queue
                .offer(DependencyChange {
                    package: format!("{}-{index}", scenario.name),
                    previous: Version::new(1, 0, index as u64),
                    selected: Version::new(1, 0, index as u64 + 1),
                    reason: "queue fixture".to_owned(),
                })
                .unwrap();
        }
        for _ in 0..scenario.drains {
            queue.take(Duration::from_millis(scenario.wait_millis)).unwrap();
        }
        assert_eq!(queue.pending(), scenario.expected_pending, "{}", scenario.name);
    }
}
