#!/usr/bin/env python3
"""Generate internal/season/heat_gen.go from config/baselines/heat.env."""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV = ROOT / "config" / "baselines" / "heat.env"
OUT = ROOT / "internal" / "season" / "heat_gen.go"

HEAT_KEYS = [
    "default_era",
    "row_slack",
    "target_pad",
    "flip_latch_seed",
    "leave_latch_seed",
    "printer_win_floor",
    "aggregate_scale",
    "majority_score",
    "championship_mode",
]

# Exhibition fallback when heat_seal does not match the key payload.
FALLBACK = {
    "default_era": "heat-v2",
    "row_slack": "1",
    "target_pad": "1",
    "flip_latch_seed": "0",
    "leave_latch_seed": "0",
    "printer_win_floor": "2",
    "aggregate_scale": "1.15",
    "majority_score": "70",
    "championship_mode": "0",
}


def parse_env(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def heat_payload(e: dict[str, str]) -> str:
    return "".join(f"{k}={e[k]}\n" for k in HEAT_KEYS)


def expected_seal(e: dict[str, str]) -> str:
    return hashlib.sha256(heat_payload(e).encode()).hexdigest()


def main() -> None:
    raw = parse_env(ENV)
    e = {k: raw.get(k, FALLBACK[k]) for k in HEAT_KEYS}
    want = expected_seal(e)
    got = raw.get("heat_seal", "").lower()
    if got != want:
        print(
            f"heat_seal mismatch (got {got or 'missing'}, want {want}); "
            "baking exhibition fallback constants",
            file=sys.stderr,
        )
        e = dict(FALLBACK)
    body = f'''// Code generated by scripts/gen_heat.py from config/baselines/heat.env. DO NOT EDIT.
package season

const HeatDefaultEra = "{e.get("default_era", "heat-v2")}"

const (
	RowSlack         = {e.get("row_slack", "1")}
	TargetPad        = {e.get("target_pad", "1")}
	FlipLatchSeed    = {e.get("flip_latch_seed", "0")}
	LeaveLatchSeed   = {e.get("leave_latch_seed", "0")}
	PrinterWinFloor  = {e.get("printer_win_floor", "2")}
	MajorityScore    = {e.get("majority_score", "70")}
)

const AggregateScale = {e.get("aggregate_scale", "1.15")}

const ChampionshipMode = {e.get("championship_mode", "0")}
'''
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
