#!/usr/bin/env python3
"""Generate internal/season/heat_gen.go from config/baselines/heat.env."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV = ROOT / "config" / "baselines" / "heat.env"
OUT = ROOT / "internal" / "season" / "heat_gen.go"


def parse_env(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def main() -> None:
    e = parse_env(ENV)
    body = f'''// Code generated by scripts/gen_heat.py from config/baselines/heat.env. DO NOT EDIT.
package season

const HeatDefaultEra = "{e.get("default_era", "heat-v2")}"

const (
	RowSlack         = {e.get("row_slack", "1")}
	TargetPad        = {e.get("target_pad", "1")}
	FlipLatchSeed    = {e.get("flip_latch_seed", "0")}
	LeaveLatchSeed   = {e.get("leave_latch_seed", "0")}
	PrinterWinFloor  = {e.get("printer_win_floor", "2")}
	MajorityScore    = {e.get("majority_score", "70")}
)

const AggregateScale = {e.get("aggregate_scale", "1.15")}

const ChampionshipMode = {e.get("championship_mode", "0")}
'''
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
